import { defineStore } from 'pinia'

export const useStoreStages = defineStore('storeStages', {
  state: () => {
    return {
      stages: [
        {
          stage: 'stage1',
          id: 'stage1niveau1',
          subStage: '1',
          type: 'Priorités de calcul',
          questions: [
            [['e','\\dfrac{2 \\times 2}{2 + 2}=']],
            [['e','2 \\times 2 - 2=']],
            [['e','\\dfrac{2\\times2\\times2-2}{2}=']],
            [['e','2\\times2-2+2=']],
            [['e','2+\\dfrac{2}{2}+2=']],
            [['e','2+2\\times2=']],
            [['e','2\\times(2+2)-\\dfrac{2}{2}=']],
            [['e','2\\times2+2\\times2=']],
            [['e','(2+2)\\times2+\\dfrac{2}{2}=']],
            [['e','(2+2\\times2)\\times2-2=']],
            [['e','2+2\\times2\\times2+2-\\dfrac{2}{2}=']],
            [['e','2\\times2\\times\\left(2+\\dfrac{2}{2}\\right)=']],
            [['e','\\dfrac{3\\times3}{3+3+3}=']],
            [['e','\\dfrac{3+3}{3}=']],
            [['e','3\\times3-(3+3)=']],
            [['e','3+\\dfrac{3}{3}=']],
            [['e','3+\\dfrac{3+3}{3}=']],
            [['e','\\dfrac{3\\times3+3\\times3}{3}=']],
            [['e','3+3\\div3+3=']],
            [['e','3\\times3-3\\div3=']],
            [['e','3\\times3\\div(3\\div3)=']],
            [['e','\\dfrac{33-3}{3}=']],
            [['e','3\\times3+3-3\\div 3=']],
            [['e','3+3\\times3=']],
            [['e','(4+4)\\div(4+4)=']],
            [['e','\\dfrac{4\\times4}{4+4}=']],
            [['e','4-\\dfrac{4}{4}=']],
            [['e','4\\div(4\\div4)=']],
            [['e','4+\\dfrac{4}{4}=']],
            [['e','4+\\dfrac{4+4}{4}=']],
            [['e','\\dfrac{44-4\\times4}{4}=']],
            [['e','4\\times4-4-4=']],
            [['e','4+\\dfrac{4\}{4}+4=']],
            [['e','\\dfrac{44-4}{4}=']],
            [['e','4\\times4-4-\\dfrac{4}{4}=']],
            [['e','4\\times4-4=']],
            [['e','\\dfrac{5+5+5+5+5}{5\\times5}=']],
            [['e','\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{5+5\\times5}{5+5}=']],
            [['e','\\dfrac{55+5}{5+5+5}=']],
            [['e','55-(5+5)\\times5=']],
            [['e','5+5\\div5=']],
            [['e','5+\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{55+5\\times5}{5+5}=']],
            [['e','\\dfrac{55-(5+5)}{5}=']],
            [['e','5+5-5+5=']],
            [['e','5+5+\\dfrac{5}{5}=']],
            [['e','\\dfrac{55+5}{5}=']]
          ],
          vrai: [[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]]],
          faux: [[['e',4]],[['e',0]],[['e',7]],[['e',0]],[['e',6]],[['e',8]],[['e',3]],[['e',16]],[['e',7]],[['e',14]],[['e',17]],[['e',9]],[['e',10]],[['e',4]],[['e',9]],[['e',2]],[['e',1]],[['e',30]],[['e',5]],[['e',0]],[['e',1]],[['e',8]],[['e',12]],[['e',18]],[['e',6]],[['e',8]],[['e',0]],[['e',1]],[['e',2]],[['e',9]],[['e',40]],[['e',16]],[['e',6]],[['e',43]],[['e',2]],[['e',0]],[['e',26]],[['e',6]],[['e',15]],[['e',66]],[['e',265]],[['e',2]],[['e',11]],[['e',65]],[['e',11]],[['e',0]],[['e',3]],[['e',56]]],
          correction: [[['e','\\dfrac{2\\times2}{2+2}=\\dfrac{4}{4}=1']],[['e','2\\times2-2=4-2=2']],[['e','\\dfrac{2\\times2\\times2-2}{2}= \\dfrac{8-2}{2}=\\dfrac{6}{2}=3']],[['e','2\\times2-2+2=4-2+2= 2+2=4']],[['e','2+\\dfrac{2}{2}+2=2+1+2=5']],[['e','2+2\\times2=2+4=6']],[['e','2\\times(2+2)-\\dfrac{2}{2}=2\\times4-1=8-1=7']],[['e','2\\times2+2\\times2=4+4=8']],[['e','(2+2)\\times2+\\dfrac{2}{2}=4\\times2+1=8+1=9']],[['e','(2+2\\times2)\\times2-2=(2+4)\\times2-2=6\\times2-2=12-2= 10']],[['e','2+2\\times2\\times2+2-\\dfrac{2}{2}=2+8+2-1=11']],[['e','4\\times(2+1)=4\\times3=12']],[['e','\\dfrac{3\\times3}{3+3+3}=\\dfrac{9}{9}=1']],[['e','\\dfrac{3+3}{3}=\\dfrac{6}{3}=2']],[['e','3\\times3-(3+3)=3\\times3-6=9-6=3']],[['e','3+\\dfrac{3}{3}=}{4}{2}{3+\\dfrac{3}{3}=3+1=4']],[['e','3+\\dfrac{3+3}{3}=3+\\dfrac{6}{3}=3+2=5']],[['e','\\dfrac{3\\times3+3\\times3}{3}=\\dfrac{9+9}{3}= \\dfrac{18}{3}=6']],[['e','3+3\\div3+3=3+1+3 =7']],[['e','3\\times3-3\\div3=9-1=8']],[['e','3\\times3\\div(3\\div3)=3\\times3\\div1= 9\\div1=9']],[['e','\\dfrac{33-3}{3}=\\dfrac{30}{3}=10']],[['e','3\\times3+3-3\\div 3=9+3-1= 11']],[['e','3+3\\times3=3+9=12']],[['e','(4+4)\\div(4+4)=8\\div8=1']],[['e','\\dfrac{4\\times4}{4+4}= \\dfrac{16}{8}=2']],[['e','4-\\dfrac{4}{4}= 4-1=3']],[['e','4\\div(4\\div4)= 4\\div1=4']],[['e','4+\\dfrac{4}{4}= 4+1=5']],[['e','4+\\dfrac{4+4}{4}=4+\\dfrac{8}{4}= 4+2=6']],[['e','\\dfrac{44-4\\times4}{4}=\\dfrac{44-16}{4}=\\dfrac{28}{4}= 7']],[['e','4\\times4-4-4= 16-4-4=12-4=8']],[['e','4+\\dfrac{4}{4}+4= 4+1+4=9']],[['e','\\dfrac{44-4}{4}=\\dfrac{40}{4}=10']],[['e','4\\times4-4-\\dfrac{4}{4}=16-4-1=12-1=11']],[['e','16-4=12']],[['e','\\dfrac{5+5+5+5+5}{5\\times5}= \\dfrac{25}{25}=1']],[['e','\\dfrac{5+5}{5}= \\dfrac{10}{5}= 2']],[['e','\\dfrac{5+5\\times5}{5+5}=\\dfrac{5+25}{10}=\\dfrac{30}{10}=3']],[['e','\\dfrac{55+5}{5+5+5}=\\dfrac{60}{15}=4']],[['e','55-(5+5)\\times5=55-10\\times5=55-50=5']],[['e','5+5\\div5=5+1=6']],[['e','5+\\dfrac{5+5}{5}=5+\\dfrac{10}{5}=5+2=7']],[['e','\\dfrac{55+5\\times5}{5+5}=\\dfrac{55+25}{10}=\\dfrac{80}{10}=8']],[['e','\\dfrac{55-(5+5)}{5}= \\dfrac{55-10}{5}=\\dfrac{45}{5}=9']],[['e','5+5-5+5=10-5+5=5+5=10']],[['e','5+5+\\dfrac{5}{5}=5+5+1=11']],[['e','\\dfrac{55+5}{5}=\\dfrac{60}{5}=12']]]
        },
        {
          stage: 'stage1',
          id: 'stage1niveau2',
          subStage: '2',
          type: 'Priorités de calcul',
          questions: [
            [['e','(4+4)\\div(4+4)=']],
            [['e','\\dfrac{4\\times4}{4+4}=']],
            [['e','4-\\dfrac{4}{4}=']],
            [['e','4\\div(4\\div4)=']],
            [['e','4+\\dfrac{4}{4}=']],
            [['e','4+\\dfrac{4+4}{4}=']],
            [['e','\\dfrac{44-4\\times4}{4}=']],
            [['e','4\\times4-4-4=']],
            [['e','4+\\dfrac{4}{4}+4=']],
            [['e','\\dfrac{44-4}{4}=']],
            [['e','4\\times4-4-\\dfrac{4}{4}=']],
            [['e','4\\times4-4=']],
            [['e','\\dfrac{5+5+5+5+5}{5\\times5}=']],
            [['e','\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{5+5\\times5}{5+5}=']],
            [['e','\\dfrac{55+5}{5+5+5}=']],
            [['e','55-(5+5)\\times5=']],
            [['e','5+5\\div5=']],
            [['e','5+\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{55+5\\times5}{5+5}=']],
            [['e','\\dfrac{55-(5+5)}{5}=']],
            [['e','5+5-5+5=']],
            [['e','5+5+\\dfrac{5}{5}=']],
            [['e','\\dfrac{55+5}{5}=']],
            [['e','\\dfrac{6+6}{6+6}=']],
            [['e','\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{6\\times6}{6+6}=']],
            [['e','6-\\dfrac{6+6}{6}=']],
            [['e','6-6\\div6=']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=']],
            [['e','6+\\dfrac{6}{6}=']],
            [['e','6+\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{66-(6+6)}{6}=']],
            [['e','\\dfrac{66-6}{6}=']],
            [['e','6+6-\\dfrac66=']],
            [['e','6\\times\\dfrac{6+6}{6}=']],
            [['e','7\\div(7\\div7)\\div7=']],
            [['e','\\dfrac{7+7}{7}=']],
            [['e','\\dfrac{7\\times7-7}{7+7}=']],
            [['e','\\dfrac{77-7\\times7}{7}=']],
            [['e','7-\\dfrac{7+7}{7}=']],
            [['e','7-\\dfrac{7}{7}=']],
            [['e','7+7\\times(7-7)=']],
            [['e','7+\\dfrac{7}{7}=']],
            [['e','\\dfrac{77-(7+7)}{7}=']],
            [['e','\\dfrac{77-7}{7}=']],
            [['e','7+\\dfrac{7+7+7+7}{7}=']],
            [['e','\\dfrac{77+7}{7}=']]
          ],
          vrai: [[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]]],
          faux: [[['e',6]],[['e',8]],[['e',0]],[['e',1]],[['e',2]],[['e',9]],[['e',40]],[['e',16]],[['e',6]],[['e',43]],[['e',2]],[['e',0]],[['e',26]],[['e',6]],[['e',15]],[['e',66]],[['e',265]],[['e',2]],[['e',11]],[['e',65]],[['e',11]],[['e',0]],[['e',3]],[['e',56]],[['e',13]],[['e',7]],[['e',12]],[['e',1]],[['e',0]],[['e',19]],[['e',2]],[['e',13]],[['e',11]],[['e',65]],[['e',1]],[['e',37]],[['e',7]],[['e',8]],[['e',55]],[['e',70]],[['e',1]],[['e',0]],[['e',91]],[['e',2]],[['e',11]],[['e',76]],[['e',29]],[['e',78]]]
        },
        {
          stage: 'stage1',
          id: 'stage1niveau3',
          subStage: '3',
          type: 'Priorités de calcul',
          questions: [
            [['e','\\dfrac{6+6}{6+6}=']],
            [['e','\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{6\\times6}{6+6}=']],
            [['e','6-\\dfrac{6+6}{6}=']],
            [['e','6-6\\div6=']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=']],
            [['e','6+\\dfrac{6}{6}=']],
            [['e','6+\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{66-(6+6)}{6}=']],
            [['e','\\dfrac{66-6}{6}=']],
            [['e','6+6-\\dfrac66=']],
            [['e','6\\times\\dfrac{6+6}{6}=']],
            [['e','7\\div(7\\div7)\\div7=']],
            [['e','\\dfrac{7+7}{7}=']],
            [['e','\\dfrac{7\\times7-7}{7+7}=']],
            [['e','\\dfrac{77-7\\times7}{7}=']],
            [['e','7-\\dfrac{7+7}{7}=']],
            [['e','7-\\dfrac{7}{7}=']],
            [['e','7+7\\times(7-7)=']],
            [['e','7+\\dfrac{7}{7}=']],
            [['e','\\dfrac{77-(7+7)}{7}=']],
            [['e','\\dfrac{77-7}{7}=']],
            [['e','7+\\dfrac{7+7+7+7}{7}=']],
            [['e','\\dfrac{77+7}{7}=']],
            [['e','\\dfrac{8+8}{8}\\times\\dfrac{8}{8+8}=']],
            [['e','\\dfrac{8+8}{8}=']],
            [['e','\\dfrac{88-8\\times8}{8}=']],
            [['e','\\dfrac{8\\times8}{8+8}=']],
            [['e','\\dfrac{88-8}{8+8}=']],
            [['e','\\dfrac{88+8}{8+8}=']],
            [['e','\\dfrac{8\\times8-8}{8}=']],
            [['e','\\dfrac{88-(8+8+8)}{8}=']],
            [['e','\\dfrac{8\\times8+8}{8}=']],
            [['e','\\dfrac{88-8}{8}=']],
            [['e','\\dfrac{88-8+8}{8}=']],
            [['e','\\dfrac{88+8}{8}=']],
            [['e','\\dfrac{99-(9\\times9+9)}{9}=']],
            [['e','\\dfrac{9+9}{9}=']],
            [['e','\\dfrac{99+9}{9+9+9+9}=']],
            [['e','\\dfrac{9\\times9-9}{9+9}=']],
            [['e','\\dfrac{99-9}{9+9}=']],
            [['e','\\dfrac{99+9}{9+9}=']],
            [['e','\\dfrac{9\\times9-(9+9)}{9}=']],
            [['e','9-\\dfrac{9}{9}=']],
            [['e','\\dfrac{99+9}{9}-\\dfrac{9+9+9}{9}=']],
            [['e','\\dfrac{99-9}{9}=']],
            [['e','\\dfrac{9+9\\times9+9}{9}=']],
            [['e','\\dfrac{99+9}{9}=']]
          ],
          vrai: [[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]]],
          faux: [[['e',13]],[['e',7]],[['e',12]],[['e',1]],[['e',0]],[['e',19]],[['e',2]],[['e',13]],[['e',11]],[['e',65]],[['e',1]],[['e',37]],[['e',7]],[['e',8]],[['e',55]],[['e',70]],[['e',1]],[['e',0]],[['e',91]],[['e',2]],[['e',11]],[['e',76]],[['e',29]],[['e',78]],[['e',17]],[['e',9]],[['e',80]],[['e',16]],[['e',95]],[['e',97]],[['e',63]],[['e',85]],[['e',65]],[['e',87]],[['e',9]],[['e',89]],[['e',3]],[['e',10]],[['e',127]],[['e',89]],[['e',107]],[['e',109]],[['e',9]],[['e',0]],[['e',99]],[['e',98]],[['e',163]],[['e',100]]]
        },
        {
          stage: 'stage2',
          id: 'stage2niveau1',
          subStage: '1',
          type: 'Images / antécédents',
          questions: [
            [['t','Dans un repère, on a représenté une fonction.'],['t',' Les images se lisent :']],
            [['t','Dans un repère, on a représenté une fonction. Les images se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les antécédents se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les images se lisent :']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(1)=3']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(2)=5']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(3)=6']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées '],['e','(1\\,;2)']],
            [['t','L\'image de '],['e','3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','4'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnéees']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-2'],['e','-1'],['e','2'],['e','4']],['tabb',['e','f(x)'],['e','5'],['e','4'],['e','3'],['e','2']]],['t','L\'image de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','Un antécédent de '],['e','1'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+3']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=5x+6'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','1'],['t',' a pour ordonnée ']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','4'],['t',' a pour abscisse ']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-01.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-02.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-03.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-04.png'],['t','Le nombre d\'antécédents de '],['e','3'],['t',' est :']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-05.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution ']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(2)=4']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(0)=3']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(4)=1']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(6)=7']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(1)=9']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(7)=3']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées'],['e','(1;2)']],
            [['t','L\'image de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','8'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','L\'image de '],['e','-3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','6'],['e','4'],['e','2'],['e','0']]],['t','L\'image de '],['e','0'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','L\'image de '],['e','2'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','2'],['e','4'],['e','6']],['tabb',['e','f(x)'],['e','2'],['e','4'],['e','6'],['e','8']]],['t','Un antécédent de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','3'],['e','-1'],['e','-3']]],['t','Un antécédent de '],['e','-3'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+4']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-5']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','9'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','3'],['t',' a pour abscisse']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+7'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','2'],['t',' a pour abscisse']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-06.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-07.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-08.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-09.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-10.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-11.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-12.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-13.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution :']]
          ],
          vrai: [
            [['t','sur l\'axe des ordonnées']],
            [['t','sur l\'axe des ordonnées']],
            [['t','sur la première ligne']],
            [['t','sur la seconde ligne']],
            [['e','3'],['t',' est l\'image de '],['e','1'],['t',' par '],['e','f.']],
            [['t','Le point '],['e','A (2\\,;5)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','3'],['t',' est un antécédent de '],['e','6.']],
            [['e','f(1)=2']],
            [['e','(3\\,;4)']],
            [['e','(5\\,;2)']],
            [['e','2']],
            [['e','-3']],
            [['e','f(7)=22']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','47.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par'],['e','f'],['t',' est '],['e','3.']],
            [['e','11']],
            [['e','1']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2.']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','3']],
            [['e','S=\\{1;3\\}']],
            [['e','4'],['t',' est l\'image de '],['e','2'],['t',' par '],['e','f']],
            [['e','3'],['t',' est l\'image de '],['e','0'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(4;1)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(6;7)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','1'],['t',' est un antécédent de '],['e','9']],
            [['e','7'],['t',' est un antécédent de '],['e','3']],
            [['e','f(1)=2']],
            [['e','(2\\,;8)']],
            [['e','(-3\\,;5)']],
            [['e','(5\\,;2)']],
            [['e','6']],
            [['e','3']],
            [['e','2']],
            [['e','3']],
            [['e','f(6)=26']],
            [['e','f(3)=7']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','13.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','26.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','5']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','6']],
            [['e','8']],
            [['e','21']],
            [['e','5']],
            [['e','4']],
            [['e','-5']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-3']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','1']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','0']],
            [['e','4']],
            [['e','S=\\{0\\,;2\\}']]
          ],
          faux: [
            [['t','sur l\'axe des abscisses']],
            [['t','sur la courbe']],
            [['t','sur la seconde ligne']],
            [['t','sur la première ligne']],
            [['e','1'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f.']],            
            [['t','Le point '],['e','A (5\\,;2)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','6'],['t',' est un antécédent de '],['e','3.']],
            [['e','f(2)=1']],
            [['e','(4\\,;3)']],
            [['e','(2\\,;5)']],
            [['e','-1']],
            [['e','3']],
            [['e','f(7)=2']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par '],['e','f'],['t',' est '],['e','7.']],
            [['e','-1']],
            [['e','7']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','\\{-3\\}']],
            [['e','2'],['t',' est l\'image de '],['e','4'],['t',' par '],['e','f']],
            [['e','0'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(1;4)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(7;6)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','9'],['t',' est un antécédent de '],['e','1']],
            [['e','3'],['t',' est un antécédent de '],['e','7']],
            [['e','f(2)=1']],
            [['e','(8\\,;2)']],
            [['e','(5\\,;-3)']],
            [['e','(2\\,;5)']],
            [['e','3']],
            [['e','1']],
            [['e','6']],
            [['e','1']],
            [['e','f(6)=1']],
            [['e','f(3)=1']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','1.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','13']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','-4']],
            [['e','0']],
            [['e','3']],
            [['e','1']],
            [['e','2']],
            [['e','9']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-2']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','0']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','2']],
            [['e','\\{0\\}']]
          ]
        },
        {
          stage: 'stage2',
          id: 'stage2niveau2',
          subStage: '2',
          type: 'Images / antécédents',
          questions: [
            [['t','Dans un repère, on a représenté une fonction.'],['t',' Les images se lisent :']],
            [['t','Dans un repère, on a représenté une fonction. Les images se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les antécédents se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les images se lisent :']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(1)=3']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(2)=5']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(3)=6']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées '],['e','(1\\,;2)']],
            [['t','L\'image de '],['e','3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','4'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnéees']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-2'],['e','-1'],['e','2'],['e','4']],['tabb',['e','f(x)'],['e','5'],['e','4'],['e','3'],['e','2']]],['t','L\'image de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','Un antécédent de '],['e','1'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+3']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=5x+6'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','1'],['t',' a pour ordonnée ']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','4'],['t',' a pour abscisse ']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-01.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-02.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-03.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-04.png'],['t','Le nombre d\'antécédents de '],['e','3'],['t',' est :']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-05.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution ']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(2)=4']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(0)=3']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(4)=1']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(6)=7']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(1)=9']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(7)=3']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées'],['e','(1;2)']],
            [['t','L\'image de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','8'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','L\'image de '],['e','-3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','6'],['e','4'],['e','2'],['e','0']]],['t','L\'image de '],['e','0'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','L\'image de '],['e','2'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','2'],['e','4'],['e','6']],['tabb',['e','f(x)'],['e','2'],['e','4'],['e','6'],['e','8']]],['t','Un antécédent de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','3'],['e','-1'],['e','-3']]],['t','Un antécédent de '],['e','-3'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+4']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-5']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','9'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','3'],['t',' a pour abscisse']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+7'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','2'],['t',' a pour abscisse']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-06.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-07.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-08.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-09.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-10.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-11.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-12.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-13.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution :']]
          ],
          vrai: [
            [['t','sur l\'axe des ordonnées']],
            [['t','sur l\'axe des ordonnées']],
            [['t','sur la première ligne']],
            [['t','sur la seconde ligne']],
            [['e','3'],['t',' est l\'image de '],['e','1'],['t',' par '],['e','f.']],
            [['t','Le point '],['e','A (2\\,;5)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','3'],['t',' est un antécédent de '],['e','6.']],
            [['e','f(1)=2']],
            [['e','(3\\,;4)']],
            [['e','(5\\,;2)']],
            [['e','2']],
            [['e','-3']],
            [['e','f(7)=22']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','47.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par'],['e','f'],['t',' est '],['e','3.']],
            [['e','11']],
            [['e','1']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2.']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','3']],
            [['e','S=\\{1;3\\}']],
            [['e','4'],['t',' est l\'image de '],['e','2'],['t',' par '],['e','f']],
            [['e','3'],['t',' est l\'image de '],['e','0'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(4;1)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(6;7)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','1'],['t',' est un antécédent de '],['e','9']],
            [['e','7'],['t',' est un antécédent de '],['e','3']],
            [['e','f(1)=2']],
            [['e','(2\\,;8)']],
            [['e','(-3\\,;5)']],
            [['e','(5\\,;2)']],
            [['e','6']],
            [['e','3']],
            [['e','2']],
            [['e','3']],
            [['e','f(6)=26']],
            [['e','f(3)=7']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','13.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','26.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','5']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','6']],
            [['e','8']],
            [['e','21']],
            [['e','5']],
            [['e','4']],
            [['e','-5']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-3']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','1']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','0']],
            [['e','4']],
            [['e','S=\\{0\\,;2\\}']]
          ],
          faux: [
            [['t','sur l\'axe des abscisses']],
            [['t','sur la courbe']],
            [['t','sur la seconde ligne']],
            [['t','sur la première ligne']],
            [['e','1'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f.']],            
            [['t','Le point '],['e','A (5\\,;2)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','6'],['t',' est un antécédent de '],['e','3.']],
            [['e','f(2)=1']],
            [['e','(4\\,;3)']],
            [['e','(2\\,;5)']],
            [['e','-1']],
            [['e','3']],
            [['e','f(7)=2']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par '],['e','f'],['t',' est '],['e','7.']],
            [['e','-1']],
            [['e','7']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','\\{-3\\}']],
            [['e','2'],['t',' est l\'image de '],['e','4'],['t',' par '],['e','f']],
            [['e','0'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(1;4)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(7;6)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','9'],['t',' est un antécédent de '],['e','1']],
            [['e','3'],['t',' est un antécédent de '],['e','7']],
            [['e','f(2)=1']],
            [['e','(8\\,;2)']],
            [['e','(5\\,;-3)']],
            [['e','(2\\,;5)']],
            [['e','3']],
            [['e','1']],
            [['e','6']],
            [['e','1']],
            [['e','f(6)=1']],
            [['e','f(3)=1']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','1.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','13']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','-4']],
            [['e','0']],
            [['e','3']],
            [['e','1']],
            [['e','2']],
            [['e','9']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-2']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','0']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','2']],
            [['e','\\{0\\}']]
          ]
        },
        { 
          stage: 'stage3',
          id: 'stage3niveau1',
          subStage: '1',
          type: 'Images / antécédents',
        },
        { 
          stage: 'stage4',
          id: 'stage4niveau1',
          subStage: '1',
          type: 'Images / antécédents',
        }
      ],
    }
  },
  actions: {
    
  },
  getters: {
    
  }
})