import { defineStore } from 'pinia'

export const useStoreStages = defineStore('storeStages', {
  state: () => {
    return {
      stages: [
        {
          stage: 'stage1',
          id: 'stage1niveau1',
          subStage: '1',
          type: 'Priorités de calcul',
          questions: [
            [['e','\\dfrac{2 \\times 2}{2 + 2}=']],
            [['e','2 \\times 2 - 2=']],
            [['e','\\dfrac{2\\times2\\times2-2}{2}=']],
            [['e','2\\times2-2+2=']],
            [['e','2+\\dfrac{2}{2}+2=']],
            [['e','2+2\\times2=']],
            [['e','2\\times(2+2)-\\dfrac{2}{2}=']],
            [['e','2\\times2+2\\times2=']],
            [['e','(2+2)\\times2+\\dfrac{2}{2}=']],
            [['e','(2+2\\times2)\\times2-2=']],
            [['e','2+2\\times2\\times2+2-\\dfrac{2}{2}=']],
            [['e','2\\times2\\times\\left(2+\\dfrac{2}{2}\\right)=']],
            [['e','\\dfrac{3\\times3}{3+3+3}=']],
            [['e','\\dfrac{3+3}{3}=']],
            [['e','3\\times3-(3+3)=']],
            [['e','3+\\dfrac{3}{3}=']],
            [['e','3+\\dfrac{3+3}{3}=']],
            [['e','\\dfrac{3\\times3+3\\times3}{3}=']],
            [['e','3+3\\div3+3=']],
            [['e','3\\times3-3\\div3=']],
            [['e','3\\times3\\div(3\\div3)=']],
            [['e','\\dfrac{33-3}{3}=']],
            [['e','3\\times3+3-3\\div 3=']],
            [['e','3+3\\times3=']],
            [['e','(4+4)\\div(4+4)=']],
            [['e','\\dfrac{4\\times4}{4+4}=']],
            [['e','4-\\dfrac{4}{4}=']],
            [['e','4\\div(4\\div4)=']],
            [['e','4+\\dfrac{4}{4}=']],
            [['e','4+\\dfrac{4+4}{4}=']],
            [['e','\\dfrac{44-4\\times4}{4}=']],
            [['e','4\\times4-4-4=']],
            [['e','4+\\dfrac{4}{4}+4=']],
            [['e','\\dfrac{44-4}{4}=']],
            [['e','4\\times4-4-\\dfrac{4}{4}=']],
            [['e','4\\times4-4=']],
            [['e','\\dfrac{5+5+5+5+5}{5\\times5}=']],
            [['e','\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{5+5\\times5}{5+5}=']],
            [['e','\\dfrac{55+5}{5+5+5}=']],
            [['e','55-(5+5)\\times5=']],
            [['e','5+5\\div5=']],
            [['e','5+\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{55+5\\times5}{5+5}=']],
            [['e','\\dfrac{55-(5+5)}{5}=']],
            [['e','5+5-5+5=']],
            [['e','5+5+\\dfrac{5}{5}=']],
            [['e','\\dfrac{55+5}{5}=']]
          ],
          vrai: [['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12]],
          faux: [['e',4],['e',0],['e',7],['e',0],['e',6],['e',8],['e',3],['e',16],['e',7],['e',14],['e',17],['e',9],['e',10],['e',4],['e',9],['e',2],['e',1],['e',30],['e',5],['e',0],['e',1],['e',8],['e',12],['e',18],['e',6],['e',8],['e',0],['e',1],['e',2],['e',9],['e',40],['e',16],['e',6],['e',43],['e',2],['e',0],['e',26],['e',6],['e',15],['e',66],['e',265],['e',2],['e',11],['e',65],['e',11],['e',0],['e',3],['e',56]]
        },
        {
          stage: 'stage1',
          id: 'stage1niveau2',
          subStage: '2',
          type: 'Priorités de calcul',
          questions: [
            [['e','(4+4)\\div(4+4)=']],
            [['e','\\dfrac{4\\times4}{4+4}=']],
            [['e','4-\\dfrac{4}{4}=']],
            [['e','4\\div(4\\div4)=']],
            [['e','4+\\dfrac{4}{4}=']],
            [['e','4+\\dfrac{4+4}{4}=']],
            [['e','\\dfrac{44-4\\times4}{4}=']],
            [['e','4\\times4-4-4=']],
            [['e','4+\\dfrac{4}{4}+4=']],
            [['e','\\dfrac{44-4}{4}=']],
            [['e','4\\times4-4-\\dfrac{4}{4}=']],
            [['e','4\\times4-4=']],
            [['e','\\dfrac{5+5+5+5+5}{5\\times5}=']],
            [['e','\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{5+5\\times5}{5+5}=']],
            [['e','\\dfrac{55+5}{5+5+5}=']],
            [['e','55-(5+5)\\times5=']],
            [['e','5+5\\div5=']],
            [['e','5+\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{55+5\\times5}{5+5}=']],
            [['e','\\dfrac{55-(5+5)}{5}=']],
            [['e','5+5-5+5=']],
            [['e','5+5+\\dfrac{5}{5}=']],
            [['e','\\dfrac{55+5}{5}=']],
            [['e','\\dfrac{6+6}{6+6}=']],
            [['e','\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{6\\times6}{6+6}=']],
            [['e','6-\\dfrac{6+6}{6}=']],
            [['e','6-6\\div6=']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=']],
            [['e','6+\\dfrac{6}{6}=']],
            [['e','6+\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{66-(6+6)}{6}=']],
            [['e','\\dfrac{66-6}{6}=']],
            [['e','6+6-\\dfrac66=']],
            [['e','6\\times\\dfrac{6+6}{6}=']],
            [['e','7\\div(7\\div7)\\div7=']],
            [['e','\\dfrac{7+7}{7}=']],
            [['e','\\dfrac{7\\times7-7}{7+7}=']],
            [['e','\\dfrac{77-7\\times7}{7}=']],
            [['e','7-\\dfrac{7+7}{7}=']],
            [['e','7-\\dfrac{7}{7}=']],
            [['e','7+7\\times(7-7)=']],
            [['e','7+\\dfrac{7}{7}=']],
            [['e','\\dfrac{77-(7+7)}{7}=']],
            [['e','\\dfrac{77-7}{7}=']],
            [['e','7+\\dfrac{7+7+7+7}{7}=']],
            [['e','\\dfrac{77+7}{7}=']]
          ],
          vrai: [['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12]],
          faux: [['e',6],['e',8],['e',0],['e',1],['e',2],['e',9],['e',40],['e',16],['e',6],['e',43],['e',2],['e',0],['e',26],['e',6],['e',15],['e',66],['e',265],['e',2],['e',11],['e',65],['e',11],['e',0],['e',3],['e',56],['e',13],['e',7],['e',12],['e',1],['e',0],['e',19],['e',2],['e',13],['e',11],['e',65],['e',1],['e',37],['e',7],['e',8],['e',55],['e',70],['e',1],['e',0],['e',91],['e',2],['e',11],['e',76],['e',29],['e',78]]
        },
        {
          stage: 'stage1',
          id: 'stage1niveau3',
          subStage: '3',
          type: 'Priorités de calcul',
          questions: [
            [['e','\\dfrac{6+6}{6+6}=']],
            [['e','\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{6\\times6}{6+6}=']],
            [['e','6-\\dfrac{6+6}{6}=']],
            [['e','6-6\\div6=']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=']],
            [['e','6+\\dfrac{6}{6}=']],
            [['e','6+\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{66-(6+6)}{6}=']],
            [['e','\\dfrac{66-6}{6}=']],
            [['e','6+6-\\dfrac66=']],
            [['e','6\\times\\dfrac{6+6}{6}=']],
            [['e','7\\div(7\\div7)\\div7=']],
            [['e','\\dfrac{7+7}{7}=']],
            [['e','\\dfrac{7\\times7-7}{7+7}=']],
            [['e','\\dfrac{77-7\\times7}{7}=']],
            [['e','7-\\dfrac{7+7}{7}=']],
            [['e','7-\\dfrac{7}{7}=']],
            [['e','7+7\\times(7-7)=']],
            [['e','7+\\dfrac{7}{7}=']],
            [['e','\\dfrac{77-(7+7)}{7}=']],
            [['e','\\dfrac{77-7}{7}=']],
            [['e','7+\\dfrac{7+7+7+7}{7}=']],
            [['e','\\dfrac{77+7}{7}=']],
            [['e','\\dfrac{8+8}{8}\\times\\dfrac{8}{8+8}=']],
            [['e','\\dfrac{8+8}{8}=']],
            [['e','\\dfrac{88-8\\times8}{8}=']],
            [['e','\\dfrac{8\\times8}{8+8}=']],
            [['e','\\dfrac{88-8}{8+8}=']],
            [['e','\\dfrac{88+8}{8+8}=']],
            [['e','\\dfrac{8\\times8-8}{8}=']],
            [['e','\\dfrac{88-(8+8+8)}{8}=']],
            [['e','\\dfrac{8\\times8+8}{8}=']],
            [['e','\\dfrac{88-8}{8}=']],
            [['e','\\dfrac{88-8+8}{8}=']],
            [['e','\\dfrac{88+8}{8}=']],
            [['e','\\dfrac{99-(9\\times9+9)}{9}=']],
            [['e','\\dfrac{9+9}{9}=']],
            [['e','\\dfrac{99+9}{9+9+9+9}=']],
            [['e','\\dfrac{9\\times9-9}{9+9}=']],
            [['e','\\dfrac{99-9}{9+9}=']],
            [['e','\\dfrac{99+9}{9+9}=']],
            [['e','\\dfrac{9\\times9-(9+9)}{9}=']],
            [['e','9-\\dfrac{9}{9}=']],
            [['e','\\dfrac{99+9}{9}-\\dfrac{9+9+9}{9}=']],
            [['e','\\dfrac{99-9}{9}=']],
            [['e','\\dfrac{9+9\\times9+9}{9}=']],
            [['e','\\dfrac{99+9}{9}=']],

          ],
          vrai: [['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12],['e',1],['e',2],['e',3],['e',4],['e',5],['e',6],['e',7],['e',8],['e',9],['e',10],['e',11],['e',12]],
          faux: [['e',13],['e',7],['e',12],['e',1],['e',0],['e',19],['e',2],['e',13],['e',11],['e',65],['e',1],['e',37],['e',7],['e',8],['e',55],['e',70],['e',1],['e',0],['e',91],['e',2],['e',11],['e',76],['e',29],['e',78],['e',17],['e',9],['e',80],['e',16],['e',95],['e',97],['e',63],['e',85],['e',65],['e',87],['e',9],['e',89],['e',3],['e',10],['e',127],['e',89],['e',107],['e',109],['e',9],['e',0],['e',99],['e',98],['e',163],['e',100]]
        },
        {
          stage: 'stage2',
          id: 'stage2niveau1',
          subStage: '1',
          type: 'Images / antécédents',
          questions: [
            // [['t','Dans un repère, on a représenté une fonction.'],['t',' Les images se lisent :']],
            // [['t','Dans un repère, on a représenté une fonction. Les images se lisent :']],
            // [['t','Dans un tableau de valeurs d\'une fonction, les antécédents se lisent :']],
            // [['t','Dans un tableau de valeurs d\'une fonction, les images se lisent :']],
            // [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(1)=3']],
            // [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(2)=5']],
            // [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(3)=6']],
            // [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées '],['e','(1;2)']],
            // [['t','L\'image de '],['e','3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','4'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnéees']],
            // [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            // [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-2'],['e','-1'],['e','2'],['e','4']],['tabb',['e','f(x)'],['e','5'],['e','4'],['e','3'],['e','2']]],['t','L\'image de '],['e','4'],['t',' est :']],
            // [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','Un antécédent de '],['e','1'],['t',' est :']],
            // [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            // [['e','f'],['t',' est définie par '],['e','f(x)=4x+3']],
            // [['e','f'],['t',' est définie par '],['e','f(x)=x+2']],
            // [['e','f'],['t',' est définie par '],['e','f(x)=5x+6'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','1'],['t',' a pour ordonnée ']],
            // [['e','f'],['t',' est définie par '],['e','f(x)=x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','4'],['t',' a pour abscisse ']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-01.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-02.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-03.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-04.png'],['t','Le nombre d\'antécédents de '],['e','3'],['t',' est :']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-05.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution ']]
          ],
          vrai: [
            // ['t','sur l\'axe des ordonnées'],
            // ['t','sur l\'axe des ordonnées'],
            // ['t','sur la première ligne'],
            // ['t','sur la seconde ligne'],
            // ['t','3 est l\'image de 1 par f'],
            // ['t','Le point A (2;5) appartient à C'],
            // ['t','3 est un antécédent de 6.'],
            // ['e','f(1)=2'],
            // ['e','(3;4)'],
            // ['e','(5;2)'],
            // ['e','2'],
            // ['e','-3'],
            // ['e','f(7)=22'],
            // ['t','L\'image de 11 par f est 47.'],
            // ['t','L\'antécédent de 5 par f est 3.'],
            // ['e','11'],
            // ['e','1'],
            ['e','f(-1)=-3'],
            ['t','L\'image par f de -3 est -2.'],
            ['t','L\'antécédent par f de 1 est -3.'],
            ['e','3'],
            ['e','S=\\{1;3\\}']
          ],
          faux: [
            // ['t','sur l\'axe des abscisses'],
            // ['t','sur la courbe'],
            // ['t','sur la seconde ligne'],
            // ['t','sur la première ligne'],
            // ['t','1 est l\'image de 3 par f'],            
            // ['t','Le point A (5;2) appartient à C'],
            // ['t','6 est un antécédent de 3'],
            // ['e','f(2)=1'],
            // ['e','(4;3)'],
            // ['e','(2;5)'],
            // ['e','-1'],
            // ['e','3'],
            // ['e','f(7)=2'],
            // ['t','L\'image de 11 par f est 2.'],
            // ['t','L\'antécédent de 5 par f est 7.'],
            // ['e','-1'],
            // ['e','7'],
            ['e','f(1)=-3'],
            ['t','L\'image par f de -3 est -0,5.'],
            ['t','L\'antécédent par f de 1 est -1.'],
            ['e','1'],
            ['e','\\{-3\\}']
          ]
        },
        {
          stage: 'stage2',
          id: 'stage2niveau2',
          subStage: '2',
          type: 'Images / antécédents',
          questions: [
            [['t','Dans un repère, on a représenté une fonction.'],['t',' Les images se lisent :']],
            [['t','Dans un repère, on a représenté une fonction. Les images se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les antécédents se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les images se lisent :']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(1)=3']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(2)=5']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(3)=6']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées '],['e','(1;2)']],
            [['t','L\'image de '],['e','3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','4'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnéees']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-2'],['e','-1'],['e','2'],['e','4']],['tabb',['e','f(x)'],['e','5'],['e','4'],['e','3'],['e','2']]],['t','L\'image de '],['e','4'],['t',' est :']]
          ],
          vrai: [
            ['t','sur l\'axe des ordonnées'],
            ['t','sur l\'axe des ordonnées'],
            ['t','sur la première ligne'],
            ['t','sur la seconde ligne'],
            ['t','3 est l\'image de 1 par f'],
            ['t','Le point A (2;5) appartient à C'],
            ['t','3 est un antécédent de 6.'],
            ['e','f(1)=2'],
            ['e','(3;4)'],
            ['e','(5;2)'],
            ['e','2']
          ],
          faux: [
            ['t','sur l\'axe des abscisses'],
            ['t','sur la courbe'],
            ['t','sur la seconde ligne'],
            ['t','sur la première ligne'],
            ['t','1 est l\'image de 3 par f'],            
            ['t','Le point A (5;2) appartient à C'],
            ['t','6 est un antécédent de 3'],
            ['e','f(2)=1'],
            ['e','(4;3)'],
            ['e','(2;5)'],
            ['e','-1']

          ]
        },
        { 
          stage: 'stage3',
          id: 'stage3niveau1',
          subStage: '1',
          type: 'Images / antécédents',
        },
        { 
          stage: 'stage4',
          id: 'stage4niveau1',
          subStage: '1',
          type: 'Images / antécédents',
        }
      ],
    }
  },
  actions: {
    
  },
  getters: {
    
  }
})