import { defineStore } from 'pinia'

export const useStoreStages = defineStore('storeStages', {
  state: () => {
    return {
      stages: [
        {
          stage: 'stage1',
          id: 'stage1niveau1',
          orientation: 'h',
          type: 'Priorités de calcul #1',
          questions: [
            [['e','\\dfrac{2 \\times 2}{2 + 2}=']],
            [['e','2 \\times 2 - 2=']],
            [['e','\\dfrac{2\\times2\\times2-2}{2}=']],
            [['e','2\\times2-2+2=']],
            [['e','2+\\dfrac{2}{2}+2=']],
            [['e','2+2\\times2=']],
            [['e','2\\times(2+2)-\\dfrac{2}{2}=']],
            [['e','2\\times2+2\\times2=']],
            [['e','(2+2)\\times2+\\dfrac{2}{2}=']],
            [['e','(2+2\\times2)\\times2-2=']],
            [['e','2+2\\times2\\times2+2-\\dfrac{2}{2}=']],
            [['e','2\\times2\\times\\left(2+\\dfrac{2}{2}\\right)=']],
            [['e','\\dfrac{3\\times3}{3+3+3}=']],
            [['e','\\dfrac{3+3}{3}=']],
            [['e','3\\times3-(3+3)=']],
            [['e','3+\\dfrac{3}{3}=']],
            [['e','3+\\dfrac{3+3}{3}=']],
            [['e','\\dfrac{3\\times3+3\\times3}{3}=']],
            [['e','3+3\\div3+3=']],
            [['e','3\\times3-3\\div3=']],
            [['e','3\\times3\\div(3\\div3)=']],
            [['e','\\dfrac{33-3}{3}=']],
            [['e','3\\times3+3-3\\div 3=']],
            [['e','3+3\\times3=']],
            [['e','(4+4)\\div(4+4)=']],
            [['e','\\dfrac{4\\times4}{4+4}=']],
            [['e','4-\\dfrac{4}{4}=']],
            [['e','4\\div(4\\div4)=']],
            [['e','4+\\dfrac{4}{4}=']],
            [['e','4+\\dfrac{4+4}{4}=']],
            [['e','\\dfrac{44-4\\times4}{4}=']],
            [['e','4\\times4-4-4=']],
            [['e','4+\\dfrac{4\}{4}+4=']],
            [['e','\\dfrac{44-4}{4}=']],
            [['e','4\\times4-4-\\dfrac{4}{4}=']],
            [['e','4\\times4-4=']],
            [['e','\\dfrac{5+5+5+5+5}{5\\times5}=']],
            [['e','\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{5+5\\times5}{5+5}=']],
            [['e','\\dfrac{55+5}{5+5+5}=']],
            [['e','55-(5+5)\\times5=']],
            [['e','5+5\\div5=']],
            [['e','5+\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{55+5\\times5}{5+5}=']],
            [['e','\\dfrac{55-(5+5)}{5}=']],
            [['e','5+5-5+5=']],
            [['e','5+5+\\dfrac{5}{5}=']],
            [['e','\\dfrac{55+5}{5}=']]
          ],
          vrai: [[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]]],
          faux: [[['e',4]],[['e',0]],[['e',7]],[['e',0]],[['e',6]],[['e',8]],[['e',3]],[['e',16]],[['e',7]],[['e',14]],[['e',17]],[['e',9]],[['e',10]],[['e',4]],[['e',9]],[['e',2]],[['e',1]],[['e',30]],[['e',5]],[['e',0]],[['e',1]],[['e',8]],[['e',12]],[['e',18]],[['e',6]],[['e',8]],[['e',0]],[['e',1]],[['e',2]],[['e',9]],[['e',40]],[['e',16]],[['e',6]],[['e',43]],[['e',2]],[['e',0]],[['e',26]],[['e',6]],[['e',15]],[['e',66]],[['e',265]],[['e',2]],[['e',11]],[['e',65]],[['e',11]],[['e',0]],[['e',3]],[['e',56]]],
          correction: [[['e','\\dfrac{2\\times2}{2+2}=\\dfrac{4}{4}=1']],[['e','2\\times2-2=4-2=2']],[['e','\\dfrac{2\\times2\\times2-2}{2}= \\dfrac{8-2}{2}=\\dfrac{6}{2}=3']],[['e','2\\times2-2+2=4-2+2= 2+2=4']],[['e','2+\\dfrac{2}{2}+2=2+1+2=5']],[['e','2+2\\times2=2+4=6']],[['e','2\\times(2+2)-\\dfrac{2}{2}=2\\times4-1=8-1=7']],[['e','2\\times2+2\\times2=4+4=8']],[['e','(2+2)\\times2+\\dfrac{2}{2}=4\\times2+1=8+1=9']],[['e','(2+2\\times2)\\times2-2=(2+4)\\times2-2=6\\times2-2=12-2= 10']],[['e','2+2\\times2\\times2+2-\\dfrac{2}{2}=2+8+2-1=11']],[['e','4\\times(2+1)=4\\times3=12']],[['e','\\dfrac{3\\times3}{3+3+3}=\\dfrac{9}{9}=1']],[['e','\\dfrac{3+3}{3}=\\dfrac{6}{3}=2']],[['e','3\\times3-(3+3)=3\\times3-6=9-6=3']],[['e','3+\\dfrac{3}{3}=}{4}{2}{3+\\dfrac{3}{3}=3+1=4']],[['e','3+\\dfrac{3+3}{3}=3+\\dfrac{6}{3}=3+2=5']],[['e','\\dfrac{3\\times3+3\\times3}{3}=\\dfrac{9+9}{3}= \\dfrac{18}{3}=6']],[['e','3+3\\div3+3=3+1+3 =7']],[['e','3\\times3-3\\div3=9-1=8']],[['e','3\\times3\\div(3\\div3)=3\\times3\\div1= 9\\div1=9']],[['e','\\dfrac{33-3}{3}=\\dfrac{30}{3}=10']],[['e','3\\times3+3-3\\div 3=9+3-1= 11']],[['e','3+3\\times3=3+9=12']],[['e','(4+4)\\div(4+4)=8\\div8=1']],[['e','\\dfrac{4\\times4}{4+4}= \\dfrac{16}{8}=2']],[['e','4-\\dfrac{4}{4}= 4-1=3']],[['e','4\\div(4\\div4)= 4\\div1=4']],[['e','4+\\dfrac{4}{4}= 4+1=5']],[['e','4+\\dfrac{4+4}{4}=4+\\dfrac{8}{4}= 4+2=6']],[['e','\\dfrac{44-4\\times4}{4}=\\dfrac{44-16}{4}=\\dfrac{28}{4}= 7']],[['e','4\\times4-4-4= 16-4-4=12-4=8']],[['e','4+\\dfrac{4}{4}+4= 4+1+4=9']],[['e','\\dfrac{44-4}{4}=\\dfrac{40}{4}=10']],[['e','4\\times4-4-\\dfrac{4}{4}=16-4-1=12-1=11']],[['e','16-4=12']],[['e','\\dfrac{5+5+5+5+5}{5\\times5}= \\dfrac{25}{25}=1']],[['e','\\dfrac{5+5}{5}= \\dfrac{10}{5}= 2']],[['e','\\dfrac{5+5\\times5}{5+5}=\\dfrac{5+25}{10}=\\dfrac{30}{10}=3']],[['e','\\dfrac{55+5}{5+5+5}=\\dfrac{60}{15}=4']],[['e','55-(5+5)\\times5=55-10\\times5=55-50=5']],[['e','5+5\\div5=5+1=6']],[['e','5+\\dfrac{5+5}{5}=5+\\dfrac{10}{5}=5+2=7']],[['e','\\dfrac{55+5\\times5}{5+5}=\\dfrac{55+25}{10}=\\dfrac{80}{10}=8']],[['e','\\dfrac{55-(5+5)}{5}= \\dfrac{55-10}{5}=\\dfrac{45}{5}=9']],[['e','5+5-5+5=10-5+5=5+5=10']],[['e','5+5+\\dfrac{5}{5}=5+5+1=11']],[['e','\\dfrac{55+5}{5}=\\dfrac{60}{5}=12']]]
        },
        {
          stage: 'stage2',
          id: 'stage2niveau1',
          orientation: 'h',
          type: 'Priorités de calcul #2',
          questions: [
            [['e','(4+4)\\div(4+4)=']],
            [['e','\\dfrac{4\\times4}{4+4}=']],
            [['e','4-\\dfrac{4}{4}=']],
            [['e','4\\div(4\\div4)=']],
            [['e','4+\\dfrac{4}{4}=']],
            [['e','4+\\dfrac{4+4}{4}=']],
            [['e','\\dfrac{44-4\\times4}{4}=']],
            [['e','4\\times4-4-4=']],
            [['e','4+\\dfrac{4}{4}+4=']],
            [['e','\\dfrac{44-4}{4}=']],
            [['e','4\\times4-4-\\dfrac{4}{4}=']],
            [['e','4\\times4-4=']],
            [['e','\\dfrac{5+5+5+5+5}{5\\times5}=']],
            [['e','\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{5+5\\times5}{5+5}=']],
            [['e','\\dfrac{55+5}{5+5+5}=']],
            [['e','55-(5+5)\\times5=']],
            [['e','5+5\\div5=']],
            [['e','5+\\dfrac{5+5}{5}=']],
            [['e','\\dfrac{55+5\\times5}{5+5}=']],
            [['e','\\dfrac{55-(5+5)}{5}=']],
            [['e','5+5-5+5=']],
            [['e','5+5+\\dfrac{5}{5}=']],
            [['e','\\dfrac{55+5}{5}=']],
            [['e','\\dfrac{6+6}{6+6}=']],
            [['e','\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{6\\times6}{6+6}=']],
            [['e','6-\\dfrac{6+6}{6}=']],
            [['e','6-6\\div6=']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=']],
            [['e','6+\\dfrac{6}{6}=']],
            [['e','6+\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{66-(6+6)}{6}=']],
            [['e','\\dfrac{66-6}{6}=']],
            [['e','6+6-\\dfrac66=']],
            [['e','6\\times\\dfrac{6+6}{6}=']],
            [['e','7\\div(7\\div7)\\div7=']],
            [['e','\\dfrac{7+7}{7}=']],
            [['e','\\dfrac{7\\times7-7}{7+7}=']],
            [['e','\\dfrac{77-7\\times7}{7}=']],
            [['e','7-\\dfrac{7+7}{7}=']],
            [['e','7-\\dfrac{7}{7}=']],
            [['e','7+7\\times(7-7)=']],
            [['e','7+\\dfrac{7}{7}=']],
            [['e','\\dfrac{77-(7+7)}{7}=']],
            [['e','\\dfrac{77-7}{7}=']],
            [['e','7+\\dfrac{7+7+7+7}{7}=']],
            [['e','\\dfrac{77+7}{7}=']]
          ],
          vrai: [[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]]],
          faux: [[['e',6]],[['e',8]],[['e',0]],[['e',1]],[['e',2]],[['e',9]],[['e',40]],[['e',16]],[['e',6]],[['e',43]],[['e',2]],[['e',0]],[['e',26]],[['e',6]],[['e',15]],[['e',66]],[['e',265]],[['e',2]],[['e',11]],[['e',65]],[['e',11]],[['e',0]],[['e',3]],[['e',56]],[['e',13]],[['e',7]],[['e',12]],[['e',1]],[['e',0]],[['e',19]],[['e',2]],[['e',13]],[['e',11]],[['e',65]],[['e',1]],[['e',37]],[['e',7]],[['e',8]],[['e',55]],[['e',70]],[['e',1]],[['e',0]],[['e',91]],[['e',2]],[['e',11]],[['e',76]],[['e',29]],[['e',78]]],
          correction: [[['e','(4+4)\\div(4+4)=8\\div8=1']],[['e','\\dfrac{4\\times4}{4+4}= \\dfrac{16}{8}=2']],[['e','4-\\dfrac{4}{4}= 4-1=3']],[['e','4\\div(4\\div4)= 4\\div1=4']],[['e','4+\\dfrac{4}{4}= 4+1=5']],[['e','4+\\dfrac{4+4}{4}=4+\\dfrac{8}{4}= 4+2=6']],[['e','\\dfrac{44-4\\times4}{4}=\\dfrac{44-16}{4}=\\dfrac{28}{4}= 7']],[['e','4\\times4-4-4= 16-4-4=12-4=8']],[['e','4+\\dfrac{4}{4}+4= 4+1+4=9']],[['e','\\dfrac{44-4}{4}=\\dfrac{40}{4}=10']],[['e','4\\times4-4-\\dfrac{4}{4}=16-4-1=12-1=11']],[['e','16-4=12']],[['e','\\dfrac{5+5+5+5+5}{5\\times5}= \\dfrac{25}{25}=1']],[['e','\\dfrac{5+5}{5}= \\dfrac{10}{5}= 2']],[['e','\\dfrac{5+5\\times5}{5+5}=\\dfrac{5+25}{10}=\\dfrac{30}{10}=3']],[['e','\\dfrac{55+5}{5+5+5}=\\dfrac{60}{15}=4']],[['e','55-(5+5)\\times5=55-10\\times5=55-50=5']],[['e','5+5\\div5=5+1=6']],[['e','5+\\dfrac{5+5}{5}=5+\\dfrac{10}{5}=5+2=7']],[['e','\\dfrac{55+5\\times5}{5+5}=\\dfrac{55+25}{10}=\\dfrac{80}{10}=8']],[['e','\\dfrac{55-(5+5)}{5}= \\dfrac{55-10}{5}=\\dfrac{45}{5}=9']],[['e','5+5-5+5=10-5+5=5+5=10']],[['e','5+5+\\dfrac{5}{5}=5+5+1=11']],[['e','\\dfrac{55+5}{5}=\\dfrac{60}{5}=12']],[['e','\\dfrac{6+6}{6+6}=\\dfrac{12}{12}=1']],[['e','\\dfrac{6+6}{6}=\\dfrac{12}{6}=2']],[['e','\\dfrac{6\\times6}{6+6}=\\dfrac{36}{12}=3']],[['e','6-\\dfrac{6+6}{6}=6-\\dfrac{12}{6}=6-2=4']],[['e','6-6\\div6=6-1=5']],[['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=\\dfrac{18}{6}\\times\\dfrac{12}{6}=3\\times2=6']],[['e','6+\\dfrac{6}{6}=6+1=7']],[['e','6+\\dfrac{6+6}{6}=6+\\dfrac{12}{6}=6+2=8']],[['e','\\dfrac{66-(6+6)}{6}=\\dfrac{66-12}{6}=\\dfrac{54}{6}=9']],[['e','\\dfrac{66-6}{6}=\\dfrac{60}{6}=10']],[['e','6+6-\\dfrac66=6+6-1=11']],[['e','6\\times\\dfrac{6+6}{6}=6\\times\\dfrac{12}{6}=6\\times2=12']],[['e','7\\div(7\\div7)\\div7=7\\div1\\div7=7\\div7=1']],[['e','\\dfrac{7+7}{7}=\\dfrac{14}{7}=2']],[['e','\\dfrac{7\\times7-7}{7+7}=\\dfrac{49-7}{14}=\\dfrac{42}{14}=3']],[['e','\\dfrac{77-7\\times7}{7}=\\dfrac{77-49}{7}=\\dfrac{28}{7}=4']],[['e','7-\\dfrac{7+7}{7}=7-\\dfrac{7+7}{7}=7-\\dfrac{14}{7}=7-2=5']],[['e','7-\\dfrac{7}{7}=7-1=6']],[['e','7+7\\times0=7+0=7']],[['e','7+\\dfrac{7}{7}=7+1=8']],[['e','\\dfrac{77-(7+7)}{7}=\\dfrac{77-14}{7}=\\dfrac{63}{7}=9']],[['e','\\dfrac{77-7}{7}=\\dfrac{70}{7}=10']],[['e','7+\\dfrac{7+7+7+7}{7}=7+\\dfrac{28}{7}=7+4=11']],[['e','\\dfrac{77+7}{7}=\\dfrac{84}{7}=12']]]
        },
        {
          stage: 'stage3',
          id: 'stage3niveau1',
          orientation: 'h',
          type: 'Priorités de calcul #3',
          questions: [
            [['e','\\dfrac{6+6}{6+6}=']],
            [['e','\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{6\\times6}{6+6}=']],
            [['e','6-\\dfrac{6+6}{6}=']],
            [['e','6-6\\div6=']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=']],
            [['e','6+\\dfrac{6}{6}=']],
            [['e','6+\\dfrac{6+6}{6}=']],
            [['e','\\dfrac{66-(6+6)}{6}=']],
            [['e','\\dfrac{66-6}{6}=']],
            [['e','6+6-\\dfrac66=']],
            [['e','6\\times\\dfrac{6+6}{6}=']],
            [['e','7\\div(7\\div7)\\div7=']],
            [['e','\\dfrac{7+7}{7}=']],
            [['e','\\dfrac{7\\times7-7}{7+7}=']],
            [['e','\\dfrac{77-7\\times7}{7}=']],
            [['e','7-\\dfrac{7+7}{7}=']],
            [['e','7-\\dfrac{7}{7}=']],
            [['e','7+7\\times(7-7)=']],
            [['e','7+\\dfrac{7}{7}=']],
            [['e','\\dfrac{77-(7+7)}{7}=']],
            [['e','\\dfrac{77-7}{7}=']],
            [['e','7+\\dfrac{7+7+7+7}{7}=']],
            [['e','\\dfrac{77+7}{7}=']],
            [['e','\\dfrac{8+8}{8}\\times\\dfrac{8}{8+8}=']],
            [['e','\\dfrac{8+8}{8}=']],
            [['e','\\dfrac{88-8\\times8}{8}=']],
            [['e','\\dfrac{8\\times8}{8+8}=']],
            [['e','\\dfrac{88-8}{8+8}=']],
            [['e','\\dfrac{88+8}{8+8}=']],
            [['e','\\dfrac{8\\times8-8}{8}=']],
            [['e','\\dfrac{88-(8+8+8)}{8}=']],
            [['e','\\dfrac{8\\times8+8}{8}=']],
            [['e','\\dfrac{88-8}{8}=']],
            [['e','\\dfrac{88-8+8}{8}=']],
            [['e','\\dfrac{88+8}{8}=']],
            [['e','\\dfrac{99-(9\\times9+9)}{9}=']],
            [['e','\\dfrac{9+9}{9}=']],
            [['e','\\dfrac{99+9}{9+9+9+9}=']],
            [['e','\\dfrac{9\\times9-9}{9+9}=']],
            [['e','\\dfrac{99-9}{9+9}=']],
            [['e','\\dfrac{99+9}{9+9}=']],
            [['e','\\dfrac{9\\times9-(9+9)}{9}=']],
            [['e','9-\\dfrac{9}{9}=']],
            [['e','\\dfrac{99+9}{9}-\\dfrac{9+9+9}{9}=']],
            [['e','\\dfrac{99-9}{9}=']],
            [['e','\\dfrac{9+9\\times9+9}{9}=']],
            [['e','\\dfrac{99+9}{9}=']]
          ],
          vrai: [[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]],[['e',1]],[['e',2]],[['e',3]],[['e',4]],[['e',5]],[['e',6]],[['e',7]],[['e',8]],[['e',9]],[['e',10]],[['e',11]],[['e',12]]],
          faux: [[['e',13]],[['e',7]],[['e',12]],[['e',1]],[['e',0]],[['e',19]],[['e',2]],[['e',13]],[['e',11]],[['e',65]],[['e',1]],[['e',37]],[['e',7]],[['e',8]],[['e',55]],[['e',70]],[['e',1]],[['e',0]],[['e',91]],[['e',2]],[['e',11]],[['e',76]],[['e',29]],[['e',78]],[['e',17]],[['e',9]],[['e',80]],[['e',16]],[['e',95]],[['e',97]],[['e',63]],[['e',85]],[['e',65]],[['e',87]],[['e',9]],[['e',89]],[['e',3]],[['e',10]],[['e',127]],[['e',89]],[['e',107]],[['e',109]],[['e',9]],[['e',0]],[['e',99]],[['e',98]],[['e',163]],[['e',100]]],
          correction: [
            [['e','\\dfrac{6+6}{6+6}=\\dfrac{12}{12}=1']],
            [['e','\\dfrac{6+6}{6}=\\dfrac{12}{6}=2']],
            [['e','\\dfrac{6\\times6}{6+6}=\\dfrac{36}{12}=3']],
            [['e','6-\\dfrac{6+6}{6}=6-\\dfrac{12}{6}=6-2=4']],
            [['e','6-6\\div6=6-1=5']],
            [['e','\\dfrac{6+6+6}{6}\\times\\dfrac{6+6}{6}=\\dfrac{18}{6}\\times\\dfrac{12}{6}=3\\times2=6']],
            [['e','6+\\dfrac{6}{6}=6+1=7']],
            [['e','6+\\dfrac{6+6}{6}=6+\\dfrac{12}{6}=6+2=8']],
            [['e','\\dfrac{66-(6+6)}{6}=\\dfrac{66-12}{6}=\\dfrac{54}{6}=9']],
            [['e','\\dfrac{66-6}{6}=\\dfrac{60}{6}=10']],
            [['e','6+6-\\dfrac66=6+6-1=11']],
            [['e','6\\times\\dfrac{6+6}{6}=6\\times\\dfrac{12}{6}=6\\times2=12']],
            [['e','7\\div(7\\div7)\\div7=7\\div1\\div7=7\\div7=1']],
            [['e','\\dfrac{7+7}{7}=\\dfrac{14}{7}=2']],
            [['e','\\dfrac{7\\times7-7}{7+7}=\\dfrac{49-7}{14}=\\dfrac{42}{14}=3']],
            [['e','\\dfrac{77-7\\times7}{7}=\\dfrac{77-49}{7}=\\dfrac{28}{7}=4']],
            [['e','7-\\dfrac{7+7}{7}=7-\\dfrac{7+7}{7}=7-\\dfrac{14}{7}=7-2=5']],
            [['e','7-\\dfrac{7}{7}=7-1=6']],
            [['e','7+7\\times0=7+0=7']],
            [['e','7+\\dfrac{7}{7}=7+1=8']],
            [['e','\\dfrac{77-(7+7)}{7}=\\dfrac{77-14}{7}=\\dfrac{63}{7}=9']],
            [['e','\\dfrac{77-7}{7}=\\dfrac{70}{7}=10']],
            [['e','7+\\dfrac{7+7+7+7}{7}=7+\\dfrac{28}{7}=7+4=11']],
            [['e','\\dfrac{77+7}{7}=\\dfrac{84}{7}=12']],
            [['e','\\dfrac{8+8}{8}\\times\\dfrac{8}{8+8}=\\dfrac{16}{8}\\times\\dfrac{8}{16}=2\\times\\dfrac12=1']],
            [['e','\\dfrac{8+8}{8}=\\dfrac{16}{8}=2']],
            [['e','\\dfrac{88-8\\times8}{8}=\\dfrac{88-64}{8}=\\dfrac{24}{8}=3']],
            [['e','\\dfrac{8\\times8}{8+8}=\\dfrac{64}{16}=4']],
            [['e','\\dfrac{88-8}{8+8}=\\dfrac{80}{16}=5']],
            [['e','\\dfrac{88+8}{8+8}=\\dfrac{96}{16}=6']],
            [['e','\\dfrac{8\\times8-8}{8}=\\dfrac{64-8}{8}=\\dfrac{56}{8}=7']],
            [['e','\\dfrac{88-(8+8+8)}{8}=\\dfrac{88-24}{8}=\\dfrac{64}{8}=8']],
            [['e','\\dfrac{8\\times8+8}{8}=\\dfrac{64+8}{8}=\\dfrac{72}{8}=9']],
            [['e','\\dfrac{88-8}{8}=\\dfrac{80}{8}=10']],
            [['e','\\dfrac{88-8+8}{8}=\\dfrac{80+8}{8}=\\dfrac{80+8}{8}=\\dfrac{88}{8}=11']],
            [['e','\\dfrac{88+8}{8}=\\dfrac{96}{8}=12']],
            [['e','\\dfrac{99-(9\\times9+9)}{9}=\\dfrac{99-(81+9)}{9}=\\dfrac{99-90}{9}=\\dfrac{9}{9}=1']],
            [['e','\\dfrac{9+9}{9}=\\dfrac{18}{9}=2']],
            [['e','\\dfrac{99+9}{9+9+9+9}=\\dfrac{108}{36}=3']],
            [['e','\\dfrac{9\\times9-9}{9+9}=\\dfrac{81-9}{18}=\\dfrac{72}{18}=4']],
            [['e','\\dfrac{99-9}{9+9}=\\dfrac{90}{18}=5']],
            [['e','\\dfrac{99+9}{9+9}=\\dfrac{108}{18}=6']],
            [['e','\\dfrac{9\\times9-(9+9)}{9}=\\dfrac{81-18}{9}=\\dfrac{63}{9}=7']],
            [['e','9-\\dfrac{9}{9}=9-1=8']],
            [['e','\\dfrac{99+9}{9}-\\dfrac{9+9+9}{9}=\\dfrac{108}{9}-\\dfrac{27}{9}=12-3=9']],
            [['e','\\dfrac{99-9}{9}=\\dfrac{90}{9}=10']],
            [['e','\\dfrac{9+9\\times9+9}{9}=\\dfrac{9+81+9}{9}=\\dfrac{99}{9}=11']],
            [['e','\\dfrac{99+9}{9}=\\dfrac{108}{9}=12']]]
        },
        {
          stage: 'stage4',
          id: 'stage4niveau1',
          orientation: 'v',
          type: 'Images / antécédents #1',
          questions: [
            [['t','Dans un repère, on a représenté une fonction.'],['t',' Les images se lisent :']],
            [['t','Dans un repère, on a représenté une fonction. Les images se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les antécédents se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les images se lisent :']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(1)=3']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(2)=5']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(3)=6']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées '],['e','(1\\,;2)']],
            [['t','L\'image de '],['e','3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','4'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnéees']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-2'],['e','-1'],['e','2'],['e','4']],['tabb',['e','f(x)'],['e','5'],['e','4'],['e','3'],['e','2']]],['t','L\'image de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','Un antécédent de '],['e','1'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+3']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=5x+6'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','1'],['t',' a pour ordonnée ']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','4'],['t',' a pour abscisse ']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-01.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-02.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-03.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-04.png'],['t','Le nombre d\'antécédents de '],['e','3'],['t',' est :']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-05.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution ']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(2)=4']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(0)=3']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(4)=1']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(6)=7']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(1)=9']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(7)=3']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées'],['e','(1;2)']],
            [['t','L\'image de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','8'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','L\'image de '],['e','-3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','6'],['e','4'],['e','2'],['e','0']]],['t','L\'image de '],['e','0'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','L\'image de '],['e','2'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','2'],['e','4'],['e','6']],['tabb',['e','f(x)'],['e','2'],['e','4'],['e','6'],['e','8']]],['t','Un antécédent de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','3'],['e','-1'],['e','-3']]],['t','Un antécédent de '],['e','-3'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+4']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-5']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','9'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','3'],['t',' a pour abscisse']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+7'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','2'],['t',' a pour abscisse']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-06.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-07.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-08.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-09.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-10.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-11.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-12.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-13.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution :']]
          ],
          vrai: [
            [['t','sur l\'axe des ordonnées']],
            [['t','sur l\'axe des ordonnées']],
            [['t','sur la première ligne']],
            [['t','sur la seconde ligne']],
            [['e','3'],['t',' est l\'image de '],['e','1'],['t',' par '],['e','f.']],
            [['t','Le point '],['e','A (2\\,;5)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','3'],['t',' est un antécédent de '],['e','6.']],
            [['e','f(1)=2']],
            [['e','(3\\,;4)']],
            [['e','(5\\,;2)']],
            [['e','2']],
            [['e','-3']],
            [['e','f(7)=22']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','47.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par'],['e','f'],['t',' est '],['e','3.']],
            [['e','11']],
            [['e','1']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2.']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','3']],
            [['e','S=\\{1;3\\}']],
            [['e','4'],['t',' est l\'image de '],['e','2'],['t',' par '],['e','f']],
            [['e','3'],['t',' est l\'image de '],['e','0'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(4;1)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(6;7)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','1'],['t',' est un antécédent de '],['e','9']],
            [['e','7'],['t',' est un antécédent de '],['e','3']],
            [['e','f(1)=2']],
            [['e','(2\\,;8)']],
            [['e','(-3\\,;5)']],
            [['e','(5\\,;2)']],
            [['e','6']],
            [['e','3']],
            [['e','2']],
            [['e','3']],
            [['e','f(6)=26']],
            [['e','f(3)=7']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','13.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','26.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','5']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','6']],
            [['e','8']],
            [['e','21']],
            [['e','5']],
            [['e','4']],
            [['e','-5']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-3']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','1']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','0']],
            [['e','4']],
            [['e','S=\\{0\\,;2\\}']]
          ],
          faux: [
            [['t','sur l\'axe des abscisses']],
            [['t','sur la courbe']],
            [['t','sur la seconde ligne']],
            [['t','sur la première ligne']],
            [['e','1'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f.']],            
            [['t','Le point '],['e','A (5\\,;2)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','6'],['t',' est un antécédent de '],['e','3.']],
            [['e','f(2)=1']],
            [['e','(4\\,;3)']],
            [['e','(2\\,;5)']],
            [['e','-1']],
            [['e','3']],
            [['e','f(7)=2']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par '],['e','f'],['t',' est '],['e','7.']],
            [['e','-1']],
            [['e','7']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','\\{-3\\}']],
            [['e','2'],['t',' est l\'image de '],['e','4'],['t',' par '],['e','f']],
            [['e','0'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(1;4)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(7;6)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','9'],['t',' est un antécédent de '],['e','1']],
            [['e','3'],['t',' est un antécédent de '],['e','7']],
            [['e','f(2)=1']],
            [['e','(8\\,;2)']],
            [['e','(5\\,;-3)']],
            [['e','(2\\,;5)']],
            [['e','3']],
            [['e','1']],
            [['e','6']],
            [['e','1']],
            [['e','f(6)=1']],
            [['e','f(3)=1']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','1.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','13']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','-4']],
            [['e','0']],
            [['e','3']],
            [['e','1']],
            [['e','2']],
            [['e','9']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-2']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','0']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','2']],
            [['e','\\{0\\}']]
          ],
          correction: [
            [['t','Sur l\'axe des ordonnées, par définition.']],
            [['t','Sur l\'axe des ordonnées, par définition.']],
            [['t','Sur la première ligne, qui commence par la variable, par définition.']],
            [['t','Sur la seconde ligne, par définition.']],
            [['e','3'],['t',' est l\'image de '],['e','1'],['t',' par '],['e','f'],['t',' par définition.']],
            [['t','Le point '],['e','A\\,$(2\\,;5)'],['t',' appartient à '],['e','\\mathcal C'],['t',', par définition']],
            [['e','3'],['t',' est un antécédent de '],['e','6'],['t',', par définition']],
            [['e','f(1)=2'],['t',' , par définition.']],
            [['e','(3\\,;4)'],['t',' , par définition.']],
            [['e','(5\\,;2)'],['t',' , par définition.']],
            [['t','La dernière colonne du tableau indique que l\'image de '],['e','4'],['t',' , est '],['e','2']],
            [['t','La première colonne de valeurs du tableau indique qu\'un antécédent de '],['e','1'],['t',' , est '],['e','3']],
            [['e','f(7)=3\\times7+1=22']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','f(11)=4\\times11+3=47']],
            [['t','L\'antécédent '],['e','x'],['t',' de 5'],['t',' par $f'],['t',' est tel que '],['e','f(x)=5'],['t',' . Ce qui équivaut à '],['e','x+2=5'],['t',' , ou encore à '],['e','x=5-2=3']],
            [['t','L\'ordonnée est '],['e','f(1)=5\\times 1+6=11']],
            [['t','L\'abscisse '],['e','x'],['t',' est telle que '],['e','f(x)=1'],['t',' . Ce qui équivaut à '],['e','x+3=4'],['t',' , ou encore à '],['e','x=4-2=1']],
            [['im','stage2niveau1-14.png'],['e','f(-1)=-3']],
            [['im','stage2niveau1-15.png'],['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2']],
            [['im','stage2niveau1-16.png'],['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['im','stage2niveau1-17.png'],['t','La droite d\'équation '],['e','y=3'],['t',' coupe la courbe en trois points (d\'abscisses '],['e','x_1'],['t',', '],['e','x_2'],['t',' et '],['e','x_3$) donc le nombre d\'antécédents de '],['e','3'],['t',' est '],['e','3']],
            [['im','stage2niveau1-18.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution '],['e','S=\\{1\\,;3\\}']],
            [['e','4'],['t',' est l\'image de '],['e','2'],['t',' par '],['e','f'],['t',', par définition']],
            [['e','3'],['t',' est l\'image de '],['e','0'],['t',' par '],['e','f'],['t',', par définition']],
            [['t','Le point '],['e','A\\,(4\\,;1)'],['t',' appartient à '],['e','\\mathcal C'],['t',', par définition']],
            [['t','Le point '],['e','A\\,(6\\,;7)'],['t',' appartient à '],['e','\\mathcal C'],['t',', par définition']],
            [['e','1'],['t',' est un antécédent de '],['e','9'],['t',', par définition']],
            [['e','7'],['t',' est un antécédent de '],['e','3'],['t',', par définition']],
            [['e','f(1)=2'],['t',', par définition']],
            [['e','(3\\,;4)'],['t',', par définition']],
            [['e','(-3\\,;5)'],['t',', par définition']],
            [['e','(5\\,;2)'],['t',', par définition']],
            [['t','La première colonne de valeurs du tableau indique que l\'image de '],['e','0'],['t',' est '],['e','6']],
            [['t','La troisième colonne de valeurs du tableau indique que l\'image de '],['e','2'],['t',' est '],['e','3']],
            [['t','La deuxième colonne de valeurs du tableau indique qu\'un antécédent de '],['e','4'],['t',' est '],['e','2']],
            [['t','La quatrième colonne de valeurs du tableau indique qu\'un antécédent de '],['e','-3'],['t',' est '],['e','3']],
            [['e','f(6)=4\\times6+2=26']],
            [['e','f(3)=2\\times3+1=7']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','f(4)=3\\times4+1=13']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','f(8)=3\times8+2=26']],
            [['t','L\'antécédent '],['e','x'],['t',' de '],['e','9'],['t',' par '],['e','f'],['t',' est tel que '],['e','f(x)=9'],['t','. Ce qui équivaut à '],['e','x+4=9'],['t',', ou encore \`a '],['e','x=9-4=5']],
            [['t','L\'antécédent '],['e','x'],['t',' de '],['e','1'],['t',' par '],['e','f'],['t',' est tel que '],['e','f(x)=1'],['t','. Ce qui équivaut à '],['e','x-5=1'],['t',', ou encore \`a '],['e','x=1+6=6']],
            [['t','L\'ordonnée est '],['e','f(2)=3\\times 2+2=9']],
            [['t','L\'ordonnée est '],['e','f(9)=2\\times 9+3=21']],
            [['t','L\'ordonnée est '],['e','f(2)=3\\times 2-1=5']],
            [['t','L\'abscisse '],['e','x'],['t',' est telle que '],['e','f(x)=3'],['t',' . Ce qui équivaut à '],['e','x-1=3'],['t',' , ou encore à '],['e','x=3+1=4']],
            [['t','L\'abscisse '],['e','x'],['t',' est telle que '],['e','f(x)=2'],['t',' . Ce qui équivaut à '],['e','x+7=2'],['t',' , ou encore à '],['e','x=2-7=-5']],
            [['im','stage2niveau1-19.png'],['e','f(-1)=-3']],
            [['im','stage2niveau1-20.png'],['t','L\'image par '],['e','f '],['t',' de '],['e','-3 '],['t',' est '],['e','-2']],
            [['im','stage2niveau1-21.png'],['t','L\'image par '],['e','f '],['t',' de '],['e','-4 '],['t',' est '],['e','-3']],
            [['im','stage2niveau1-22.png'],['t','L\'antécédent par '],['e','f '],['t',' de '],['e','4 '],['t',' est '],['e','1']],
            [['im','stage2niveau1-23.png'],['t','L\'antécédent par '],['e','f '],['t',' de '],['e','1 '],['t',' est '],['e','-3']],
            [['im','stage2niveau1-24.png'],['t','La droite d\'\'equation '],['e','y=1'],['t',' ne coupe pas la courbe donc '],['e','1'],['t',' n\'a pas d\'antécédent (le nombre d\'antécédents de '],['e','1'],['t',' est '],['e','0)']],
            [['im','stage2niveau1-25.png'],['t','La droite d\'équation '],['e','y=1'],['t',' coupe la courbe en quatre points (d\'abscisses '],['e','x_1'],['t',', '],['e','x_2'],['t',', '],['e','x_3'],['t',', et '],['e','x_4'],['t',') donc le nombre d\'antécédents de '],['e','1'],['t','est '],['e','4'],['t','.\\(Il ne faut pas compter que les points à coordonnées entières !']],
            [['im','stage2niveau1-26.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution '],['e','S=\\{0\\,;2\\}']]
          ]
        },
        {
          stage: 'stage5',
          id: 'stage5niveau1',
          orientation: 'v',
          type: 'Images / antécédents #2',
          questions: [
            [['t','Dans un repère, on a représenté une fonction.'],['t',' Les images se lisent :']],
            [['t','Dans un repère, on a représenté une fonction. Les images se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les antécédents se lisent :']],
            [['t','Dans un tableau de valeurs d\'une fonction, les images se lisent :']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(1)=3']],
            [['t','La fonction  '],['e','f'],['t',' est telle que '],['e','f(2)=5']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(3)=6']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées '],['e','(1\\,;2)']],
            [['t','L\'image de '],['e','3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','4'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnéees']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-2'],['e','-1'],['e','2'],['e','4']],['tabb',['e','f(x)'],['e','5'],['e','4'],['e','3'],['e','2']]],['t','L\'image de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','Un antécédent de '],['e','1'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+3']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=5x+6'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','1'],['t',' a pour ordonnée ']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','4'],['t',' a pour abscisse ']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-01.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-02.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-03.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-04.png'],['t','Le nombre d\'antécédents de '],['e','3'],['t',' est :']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-05.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution ']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(2)=4']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(0)=3']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(4)=1']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(6)=7']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(1)=9']],
            [['t','La fonction '],['e','f'],['t',' est telle que '],['e','f(7)=3']],
            [['t','La courbe représentative de la fonction '],['e','f'],['t',' passe par le point de coordonnées'],['e','(1;2)']],
            [['t','L\'image de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','8'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','L\'image de '],['e','-3'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Un antécédent de '],['e','2'],['t',' par la fonction '],['e','f'],['t',' est '],['e','5'],['t','. La courbe représentative de '],['e','f'],['t',' passe par le point de coordonnées']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','6'],['e','4'],['e','2'],['e','0']]],['t','L\'image de '],['e','0'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','1'],['e','2'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','2'],['e','3'],['e','4']]],['t','L\'image de '],['e','2'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','0'],['e','2'],['e','4'],['e','6']],['tabb',['e','f(x)'],['e','2'],['e','4'],['e','6'],['e','8']]],['t','Un antécédent de '],['e','4'],['t',' est :']],
            [['t','Voici le tableau de valeurs d\'une fonction '],['e','f'],[['tabh',['e','x'],['e','-3'],['e','-1'],['e','1'],['e','3']],['tabb',['e','f(x)'],['e','1'],['e','3'],['e','-1'],['e','-3']]],['t','Un antécédent de '],['e','-3'],['t',' est :']],
            [['e','f'],['t',' est définie par '],['e','f(x)=4x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+1']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+4']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-5']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x+2'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=2x+3'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','9'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=3x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'abscisse '],['e','2'],['t',' a pour ordonnée']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x-1'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','3'],['t',' a pour abscisse']],
            [['e','f'],['t',' est définie par '],['e','f(x)=x+7'],['t','. Le point de la courbe représentative de '],['e','f'],['t',' d\'ordonnée '],['e','2'],['t',' a pour abscisse']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-06.png']],
            [['t','Voici la courbe représentant une fonction '],['e','f'],['im','stage2niveau1-07.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-08.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-09.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-10.png']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-11.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-12.png'],['t','Le nombre d\'antécédents de '],['e','1'],['t',' est :']],
            [['t','Voici la courbe représentative d\'une fonction '],['e','f'],['im','stage2niveau1-13.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution :']]
          ],
          vrai: [
            [['t','sur l\'axe des ordonnées']],
            [['t','sur l\'axe des ordonnées']],
            [['t','sur la première ligne']],
            [['t','sur la seconde ligne']],
            [['e','3'],['t',' est l\'image de '],['e','1'],['t',' par '],['e','f.']],
            [['t','Le point '],['e','A (2\\,;5)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','3'],['t',' est un antécédent de '],['e','6.']],
            [['e','f(1)=2']],
            [['e','(3\\,;4)']],
            [['e','(5\\,;2)']],
            [['e','2']],
            [['e','-3']],
            [['e','f(7)=22']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','47.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par'],['e','f'],['t',' est '],['e','3.']],
            [['e','11']],
            [['e','1']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2.']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','3']],
            [['e','S=\\{1;3\\}']],
            [['e','4'],['t',' est l\'image de '],['e','2'],['t',' par '],['e','f']],
            [['e','3'],['t',' est l\'image de '],['e','0'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(4;1)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(6;7)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','1'],['t',' est un antécédent de '],['e','9']],
            [['e','7'],['t',' est un antécédent de '],['e','3']],
            [['e','f(1)=2']],
            [['e','(2\\,;8)']],
            [['e','(-3\\,;5)']],
            [['e','(5\\,;2)']],
            [['e','6']],
            [['e','3']],
            [['e','2']],
            [['e','3']],
            [['e','f(6)=26']],
            [['e','f(3)=7']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','13.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','26.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','5']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','6']],
            [['e','8']],
            [['e','21']],
            [['e','5']],
            [['e','4']],
            [['e','-5']],
            [['e','f(-1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-3']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','1']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['e','0']],
            [['e','4']],
            [['e','S=\\{0\\,;2\\}']]
          ],
          faux: [
            [['t','sur l\'axe des abscisses']],
            [['t','sur la courbe']],
            [['t','sur la seconde ligne']],
            [['t','sur la première ligne']],
            [['e','1'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f.']],            
            [['t','Le point '],['e','A (5\\,;2)'],['t',' appartient à '],['e','\\mathcal C.']],
            [['e','6'],['t',' est un antécédent de '],['e','3.']],
            [['e','f(2)=1']],
            [['e','(4\\,;3)']],
            [['e','(2\\,;5)']],
            [['e','-1']],
            [['e','3']],
            [['e','f(7)=2']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','5'],['t',' par '],['e','f'],['t',' est '],['e','7.']],
            [['e','-1']],
            [['e','7']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','\\{-3\\}']],
            [['e','2'],['t',' est l\'image de '],['e','4'],['t',' par '],['e','f']],
            [['e','0'],['t',' est l\'image de '],['e','3'],['t',' par '],['e','f']],
            [['t','Le point '],['e','A(1;4)'],['t',' appartient à '],['e','\\mathcal C']],
            [['t','Le point '],['e','A(7;6)'],['t',' appartient à '],['e','\\mathcal C']],
            [['e','9'],['t',' est un antécédent de '],['e','1']],
            [['e','3'],['t',' est un antécédent de '],['e','7']],
            [['e','f(2)=1']],
            [['e','(8\\,;2)']],
            [['e','(5\\,;-3)']],
            [['e','(2\\,;5)']],
            [['e','3']],
            [['e','1']],
            [['e','6']],
            [['e','1']],
            [['e','f(6)=1']],
            [['e','f(3)=1']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','1.']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','2.']],
            [['t','L\'antécédent de '],['e','9'],['t',' par '],['e','f'],['t',' est '],['e','13']],
            [['t','L\'antécédent de '],['e','1'],['t',' par '],['e','f'],['t',' est '],['e','-4']],
            [['e','0']],
            [['e','3']],
            [['e','1']],
            [['e','2']],
            [['e','9']],
            [['e','f(1)=-3']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-0,5']],
            [['t','L\'image par '],['e','f'],['t',' de '],['e','-4'],['t',' est '],['e','-2']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','4'],['t',' est '],['e','0']],
            [['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-1']],
            [['e','1']],
            [['e','2']],
            [['e','\\{0\\}']]
          ],
          correction: [
            [['t','Sur l\'axe des ordonnées, par définition.']],
            [['t','Sur l\'axe des ordonnées, par définition.']],
            [['t','Sur la première ligne, qui commence par la variable, par définition.']],
            [['t','Sur la seconde ligne, par définition.']],
            [['e','3'],['t',' est l\'image de '],['e','1'],['t',' par '],['e','f'],['t',' par définition.']],
            [['t','Le point '],['e','A\\,$(2\\,;5)'],['t',' appartient à '],['e','\\mathcal C'],['t',', par définition']],
            [['e','3'],['t',' est un antécédent de '],['e','6'],['t',', par définition']],
            [['e','f(1)=2'],['t',' , par définition.']],
            [['e','(3\\,;4)'],['t',' , par définition.']],
            [['e','(5\\,;2)'],['t',' , par définition.']],
            [['t','La dernière colonne du tableau indique que l\'image de '],['e','4'],['t',' , est '],['e','2']],
            [['t','La première colonne de valeurs du tableau indique qu\'un antécédent de '],['e','1'],['t',' , est '],['e','3']],
            [['e','f(7)=3\\times7+1=22']],
            [['t','L\'image de '],['e','11'],['t',' par '],['e','f'],['t',' est '],['e','f(11)=4\\times11+3=47']],
            [['t','L\'antécédent '],['e','x'],['t',' de 5'],['t',' par $f'],['t',' est tel que '],['e','f(x)=5'],['t',' . Ce qui équivaut à '],['e','x+2=5'],['t',' , ou encore à '],['e','x=5-2=3']],
            [['t','L\'ordonnée est '],['e','f(1)=5\\times 1+6=11']],
            [['t','L\'abscisse '],['e','x'],['t',' est telle que '],['e','f(x)=1'],['t',' . Ce qui équivaut à '],['e','x+3=4'],['t',' , ou encore à '],['e','x=4-2=1']],
            [['im','stage2niveau1-14.png'],['e','f(-1)=-3']],
            [['im','stage2niveau1-15.png'],['t','L\'image par '],['e','f'],['t',' de '],['e','-3'],['t',' est '],['e','-2']],
            [['im','stage2niveau1-16.png'],['t','L\'antécédent par '],['e','f'],['t',' de '],['e','1'],['t',' est '],['e','-3']],
            [['im','stage2niveau1-17.png'],['t','La droite d\'équation '],['e','y=3'],['t',' coupe la courbe en trois points (d\'abscisses '],['e','x_1'],['t',', '],['e','x_2'],['t',' et '],['e','x_3$) donc le nombre d\'antécédents de '],['e','3'],['t',' est '],['e','3']],
            [['im','stage2niveau1-18.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution '],['e','S=\\{1\\,;3\\}']],
            [['e','4'],['t',' est l\'image de '],['e','2'],['t',' par '],['e','f'],['t',', par définition']],
            [['e','3'],['t',' est l\'image de '],['e','0'],['t',' par '],['e','f'],['t',', par définition']],
            [['t','Le point '],['e','A\\,(4\\,;1)'],['t',' appartient à '],['e','\\mathcal C'],['t',', par définition']],
            [['t','Le point '],['e','A\\,(6\\,;7)'],['t',' appartient à '],['e','\\mathcal C'],['t',', par définition']],
            [['e','1'],['t',' est un antécédent de '],['e','9'],['t',', par définition']],
            [['e','7'],['t',' est un antécédent de '],['e','3'],['t',', par définition']],
            [['e','f(1)=2'],['t',', par définition']],
            [['e','(3\\,;4)'],['t',', par définition']],
            [['e','(-3\\,;5)'],['t',', par définition']],
            [['e','(5\\,;2)'],['t',', par définition']],
            [['t','La première colonne de valeurs du tableau indique que l\'image de '],['e','0'],['t',' est '],['e','6']],
            [['t','La troisième colonne de valeurs du tableau indique que l\'image de '],['e','2'],['t',' est '],['e','3']],
            [['t','La deuxième colonne de valeurs du tableau indique qu\'un antécédent de '],['e','4'],['t',' est '],['e','2']],
            [['t','La quatrième colonne de valeurs du tableau indique qu\'un antécédent de '],['e','-3'],['t',' est '],['e','3']],
            [['e','f(6)=4\\times6+2=26']],
            [['e','f(3)=2\\times3+1=7']],
            [['t','L\'image de '],['e','4'],['t',' par '],['e','f'],['t',' est '],['e','f(4)=3\\times4+1=13']],
            [['t','L\'image de '],['e','8'],['t',' par '],['e','f'],['t',' est '],['e','f(8)=3\times8+2=26']],
            [['t','L\'antécédent '],['e','x'],['t',' de '],['e','9'],['t',' par '],['e','f'],['t',' est tel que '],['e','f(x)=9'],['t','. Ce qui équivaut à '],['e','x+4=9'],['t',', ou encore \`a '],['e','x=9-4=5']],
            [['t','L\'antécédent '],['e','x'],['t',' de '],['e','1'],['t',' par '],['e','f'],['t',' est tel que '],['e','f(x)=1'],['t','. Ce qui équivaut à '],['e','x-5=1'],['t',', ou encore \`a '],['e','x=1+6=6']],
            [['t','L\'ordonnée est '],['e','f(2)=3\\times 2+2=9']],
            [['t','L\'ordonnée est '],['e','f(9)=2\\times 9+3=21']],
            [['t','L\'ordonnée est '],['e','f(2)=3\\times 2-1=5']],
            [['t','L\'abscisse '],['e','x'],['t',' est telle que '],['e','f(x)=3'],['t',' . Ce qui équivaut à '],['e','x-1=3'],['t',' , ou encore à '],['e','x=3+1=4']],
            [['t','L\'abscisse '],['e','x'],['t',' est telle que '],['e','f(x)=2'],['t',' . Ce qui équivaut à '],['e','x+7=2'],['t',' , ou encore à '],['e','x=2-7=-5']],
            [['im','stage2niveau1-19.png'],['e','f(-1)=-3']],
            [['im','stage2niveau1-20.png'],['t','L\'image par '],['e','f '],['t',' de '],['e','-3 '],['t',' est '],['e','-2']],
            [['im','stage2niveau1-21.png'],['t','L\'image par '],['e','f '],['t',' de '],['e','-4 '],['t',' est '],['e','-3']],
            [['im','stage2niveau1-22.png'],['t','L\'antécédent par '],['e','f '],['t',' de '],['e','4 '],['t',' est '],['e','1']],
            [['im','stage2niveau1-23.png'],['t','L\'antécédent par '],['e','f '],['t',' de '],['e','1 '],['t',' est '],['e','-3']],
            [['im','stage2niveau1-24.png'],['t','La droite d\'\'equation '],['e','y=1'],['t',' ne coupe pas la courbe donc '],['e','1'],['t',' n\'a pas d\'antécédent (le nombre d\'antécédents de '],['e','1'],['t',' est '],['e','0)']],
            [['im','stage2niveau1-25.png'],['t','La droite d\'équation '],['e','y=1'],['t',' coupe la courbe en quatre points (d\'abscisses '],['e','x_1'],['t',', '],['e','x_2'],['t',', '],['e','x_3'],['t',', et '],['e','x_4'],['t',') donc le nombre d\'antécédents de '],['e','1'],['t','est '],['e','4'],['t','.\\(Il ne faut pas compter que les points à coordonnées entières !']],
            [['im','stage2niveau1-26.png'],['t','L\'équation '],['e','f(x)=0'],['t',' a pour solution '],['e','S=\\{0\\,;2\\}']]
          ]
        },
        {
          stage: 'stage6',
          id: 'stage6niveau1',
          orientation: 'h',
          type: 'Conversions',
          questions:[
            [['e','3,4~m~=~...~cm']],
            [['e','2,623~m~=~...~cm']],
            [['e','35~dm~=~...~m']],
            [['e','14~hm~=~...~m']],
            [['e','300~dm~=~...~cm']],
            [['e','700~m~=~...~cm']],
            [['e','40~m~=~...~dm']],
            [['e','50~dm~=~...~m']],
            [['e','32~cm~=~...~dm']],
            [['e','10,5~cm~=~...~dm']],
            [['e','300,8~cm~=~...~m']],
            [['e','900~dm~=~...~cm']],
            [['e','1~m~=~...~mm']],
            [['e','1~dam~=~...~m']],
            [['e','1~cm~=~...~m']],
            [['e','25,314~m~=~...~cm']],
            [['e','43,25~m~=~...~cm']],
            [['e','195~m~=~...~km']],
            [['e','8,2~m~=~...~cm']],
            [['e','23~dm~=~...~cm']],
            [['e','45~dm~=~...~cm']],
            [['e','22,3~m~=~...~mm']],
            [['e','0,56~m~=~...~mm']],
            [['e','720~m~=~...~km']],
            [['e','134,265~m~=~...~cm']],
            [['e','600~m~=~...~km']],
            [['e','7,20~m~=~...~cm']],
            [['e','4~587~dm~=~...~dam']],
            [['e','2,5~km~=~25~...']],
            [['e','0,001~dam~=~10~...']],
            [['e','5~000~dm~=~50~...']],
            [['e','300~dm~=~3~...']],
            [['e','0,37~dm~=~37~...']],
            [['e','2~538~m~=~25,38~...']],
            [['e','6,487~km~=~64~870~...']],
            [['e','12~567,9~cm~=~12,567~9~...']],
            [['e','6~753~mm~=~0,006~753~...']],
            [['e','12~000~cm~=~12~...']],
            [['e','40,305~m~=~...~m']],
            [['e','12~cm~=~...~mm']],
            [['e','3,4~dm~=~340~...']],
            [['e','12,56~m~=~12~560~...']],
          ],
          vrai:[
            [['e','340~cm']],
            [['e','262,3~cm']],
            [['e','3,5~m']],
            [['e','1~400~m']],
            [['e','3~000~cm']],
            [['e','70~000~cm']],
            [['e','400~dm']],
            [['e','5~m']],
            [['e','3,2~dm']],
            [['e','1,05~dm']],
            [['e','3,008~m']],
            [['e','9~000~cm']],
            [['e','1~000~mm']],
            [['e','10~m']],
            [['e','0,01~m']],
            [['e','25,314~cm']],
            [['e','4~325~cm']],
            [['e','0,195~km']],
            [['e','820~cm']],
            [['e','230~cm']],
            [['e','450~cm']],
            [['e','22~300~mm']],
            [['e','560~mm']],
            [['e','0,72~km']],
            [['e','13~426,5~cm']],
            [['e','0,6~km']],
            [['e','720~cm']],
            [['e','45,87~dam']],
            [['e','25~hm']],
            [['e','10~mm']],
            [['e','50~dam']],
            [['e','0,3~hm']],
            [['e','37~mm']],
            [['e','25,38~hm']],
            [['e','64~870~dm']],
            [['e','12~567,9~dam']],
            [['e','0,006~753~km']],
            [['e','12~dam']],
            [['e','4~030,5~cm']],
            [['e','120~mm']],
            [['e','340~mm']],
            [['e','12~560~mm']]
          ],
          faux:[
            [['e','300,4~cm']],
            [['e','2~623~cm']],
            [['e','350~m']],
            [['e','140~m']],
            [['e','30~cm']],
            [['e','7~cm']],
            [['e','4~dm']],
            [['e','500~m']],
            [['e','320~dm']],
            [['e','105~dm']],
            [['e','3,8~m']],
            [['e','90~cm']],
            [['e','100~mm']],
            [['e','0,1~m']],
            [['e','100~m']],
            [['e','25~314~cm']],
            [['e','432,5~cm']],
            [['e','0,00195~km']],
            [['e','800,2~cm']],
            [['e','2~300~cm']],
            [['e','4,5~cm']],
            [['e','2~230~mm']],
            [['e','56~000~mm']],
            [['e','72~km']],
            [['e','134~265~cm']],
            [['e','0,06~km']],
            [['e','7,2000~cm']],
            [['e','458,7~dam']],
            [['e','25~dam']],
            [['e','10~cm']],
            [['e','50~hm']],
            [['e','3~m']],
            [['e','37~cm']],
            [['e','25,38~km']],
            [['e','64~870~m']],
            [['e','12~567,9~hm']],
            [['e','0,006~753~hm']],
            [['e','12~m']],
            [['e','4~000,305~cm']],
            [['e','1,2~mm']],
            [['e','340~cm']],
            [['e','12~560~dm']]
          ],
          correction:[
            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','3,'],['e','4'],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','3'],['e','4'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','2,'],['e','6'],['e','2'],['e','3']],['tabb',['e',''],['e',''],['e',''],['e','2'],['e','6'],['e','2,'],['e','3']]]],
            
            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','3'],['e','5'],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','3,'],['e','5'],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e','1'],['e','4'],['e',''],['e',''],['e',''],['e',''],['e','']],['tabb',['e','1'],['e','4'],['e','0'],['e','0'],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','3'],['e','0'],['e','0'],['e',''],['e','']],['tabb',['e',''],['e',''],['e','3'],['e','0'],['e','0'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','7'],['e','0'],['e','0'],['e',''],['e',''],['e','']],['tabb',['e',''],['e','7'],['e','0'],['e','0'],['e','0'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','4'],['e','0'],['e',''],['e',''],['e','']],['tabb',['e',''],['e',''],['e','4'],['e','0'],['e','0'],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','5'],['e','0'],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','5'],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','3'],['e','2'],['e','']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','3,'],['e','2'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','1'],['e','0,'],['e','5']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','1,'],['e','0'],['e','5']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','3'],['e','0'],['e','0,'],['e','8']],['tabb',['e',''],['e',''],['e',''],['e','3,'],['e','0'],['e','0'],['e','8']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','9'],['e','0'],['e','0'],['e',''],['e','']],['tabb',['e',''],['e',''],['e','9'],['e','0'],['e','0'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','1'],['e',''],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','1'],['e','0'],['e','0'],['e','0']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','1'],['e',''],['e',''],['e',''],['e','']],['tabb',['e',''],['e',''],['e','1'],['e','0'],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e',''],['e',''],['e','1'],['e','']],['tabb',['e',''],['e',''],['e',''],['e','0,'],['e','0'],['e','1'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','2'],['e','5,'],['e','3'],['e','1'],['e','4']],['tabb',['e',''],['e',''],['e','2'],['e','5'],['e','3'],['e','1,'],['e','4']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','4'],['e','3,'],['e','2'],['e','5'],['e','']],['tabb',['e',''],['e',''],['e','4'],['e','3'],['e','2,'],['e','5'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','1'],['e','9'],['e','5'],['e',''],['e',''],['e','']],['tabb',['e','0,'],['e','1'],['e','9'],['e','5'],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','8,'],['e','2'],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','8'],['e','2'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','2'],['e','3'],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','2'],['e','3'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','4'],['e','5'],['e',''],['e','']],['tabb',['e',''],['e',''],['e',''],['e','4'],['e','5'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','2'],['e','2,'],['e','3'],['e',''],['e','']],['tabb',['e',''],['e',''],['e','2'],['e','2'],['e','3'],['e','0'],['e','0']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','0,'],['e','5'],['e','6'],['e','']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','5'],['e','6'],['e','0']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','7'],['e','2'],['e','0'],['e',''],['e',''],['e','']],['tabb',['e','0,'],['e','7'],['e','2'],['e',''],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','1'],['e','3'],['e','4,'],['e','2'],['e','6'],['e','5']],['tabb',['e',''],['e','1'],['e','3'],['e','4'],['e','2'],['e','6,'],['e','5']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','6'],['e','0'],['e','0'],['e',''],['e',''],['e','']],['tabb',['e','0,'],['e','6'],['e',''],['e',''],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','7,'],['e','2'],['e','0'],['e','']],['tabb',['e',''],['e',''],['e',''],['e','7'],['e','2'],['e','0'],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','4'],['e','5'],['e','8'],['e','7'],['e',''],['e','']],['tabb',['e',''],['e','4'],['e','5,'],['e','8'],['e','7'],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e','2,'],['e','5'],['e',''],['e',''],['e',''],['e',''],['e','']],['tabb',['e','2'],['e','5'],['e',''],['e',''],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','0,'],['e','0'],['e','0'],['e','1'],['e','']],['tabb',['e',''],['e',''],['e',''],['e',''],['e',''],['e','1'],['e','0']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','5'],['e','0'],['e','0'],['e','0'],['e',''],['e','']],['tabb',['e',''],['e','5'],['e','0'],['e',''],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','3'],['e','0'],['e','0'],['e',''],['e','']],['tabb',['e',''],['e',''],['e','3'],['e',''],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','0,'],['e','3'],['e','7']],['tabb',['e',''],['e',''],['e',''],['e',''],['e',''],['e','3'],['e','7']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e','2'],['e','5'],['e','3'],['e','8'],['e',''],['e',''],['e','']],['tabb',['e','2'],['e','5,'],['e','3'],['e','8'],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e','6,'],['e','4'],['e','8'],['e','7'],['e',''],['e',''],['e','']],['tabb',['e','6'],['e','4'],['e','8'],['e','7'],['e','0'],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','1'],['e','2'],['e','5'],['e','6'],['e','7,'],['e','9']],['tabb',['e',''],['e','1'],['e','2,'],['e','5'],['e','6'],['e','7'],['e','9']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e','6'],['e','7'],['e','5'],['e','3']],['tabb',['e','0,'],['e','0'],['e','0'],['e','6'],['e','7'],['e','5'],['e','3']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e','1'],['e','2'],['e','0'],['e','0'],['e','0'],['e','']],['tabb',['e',''],['e','1'],['e','2'],['e',''],['e',''],['e',''],['e','']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','4'],['e','0,'],['e','3'],['e','0'],['e','5']],['tabb',['e',''],['e',''],['e','4'],['e','0'],['e','3'],['e','0,'],['e','5']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','1'],['e','2'],['e','']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','1'],['e','2'],['e','0']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','3,'],['e','4'],['e','']],['tabb',['e',''],['e',''],['e',''],['e',''],['e','3'],['e','4'],['e','0']]]],

            [[['tabh',['e','km'],['e','hm'],['e','dam'],['e','m'],['e','dm'],['e','cm'],['e','mm']],['tabb',['e',''],['e',''],['e','1'],['e','2,'],['e','5'],['e','6'],['e','']],['tabb',['e',''],['e',''],['e','1'],['e','2'],['e','5'],['e','6'],['e','0']]]]
          ]
        },
        {
          stage: 'stage7',
          id: 'stage7niveau1',
          orientation: 'h',
          type: 'Quadrilatères #1',
          questions:[
            [['t','Une figure plane ayant 4 côtés est un :']],
            [['t','Une figure plane ayant 2 diagonales est un :']],
            [['t','Un quadrilatère ayant 3 côtés de même longueur est un :']],
            [['t','Un quadrilatère ayant 3 angles droit est un :']],
            [['t','Un quadrilatère ayant 2 côtés opposés parallèle et de même longueur est un :']],
            [['t','Un quadrilatère ayant ses côtés opposés de même longueur 2 à 2 est un :']],
            [['t','Un quadrilatère ayant ses angles opposés de même mesure 2 à 2 est un :']],
            [['t','Un quadrilatère ayant ses diagonales qui se coupent en leur milieu est un :']],
            [['t','Un parallélogramme ayant 2 côtés consécutif perpendiculaire est un :']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur est un :']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur est un :']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire est un :']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur et perpendiculaire est un  losange :']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs perpendiculaire et de même longueur est un  carré :']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur et perpendiculaire est un rectangle :']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire et de même longueur est un carré :']],
            [['t','Un [...] ayant ses diagonales perpendiculaire est un carré.']],
            [['t','Un [...] ayant 2 côtés consécutifs de même longueur est un carré.']],
            [['t','Un [...] ayant ses diagonales de même longueur est un carré.']],
            [['t','Un [...] ayant 2 côtés consécutifs perpendiculaire est un carré.']],
            [['im','stage3niveau1-01.png']],
            [['im','stage3niveau1-02.png']],
            [['im','stage3niveau1-03.png']],
            [['im','stage3niveau1-04.png']],
            [['im','stage3niveau1-05.png']],
            [['im','stage3niveau1-06.png']],
            [['im','stage3niveau1-07.png']],
            [['im','stage3niveau1-08.png']],
            [['im','stage3niveau1-09.png']],
            [['im','stage3niveau1-10.png']],
            [['im','stage3niveau1-11.png']],
            [['im','stage3niveau1-12.png']],
            [['im','stage3niveau1-13.png']],
            [['im','stage3niveau1-14.png']],
            [['im','stage3niveau1-15.png']],
            [['im','stage3niveau1-16.png']],
            [['im','stage3niveau1-17.png']],
            [['im','stage3niveau1-18.png']],
            [['im','stage3niveau1-19.png']],
            [['im','stage3niveau1-20.png']]
          ],
          vrai:[
            [['t','quadrilatère']],
            [['t','quadrilatère']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','losange']],
            [['t','faux']],
            [['t','vrai']],
            [['t','faux']],
            [['t','vrai']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','losange']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','parallélogramme']],
            [['t','losange']],
            [['t','parallélogramme']],
            [['t','rectangle']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','losange']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','quadrilatère']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','quadrilatère']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','quadrilatère']],
            [['t','carré']]
          ],
          faux:[
            [['t','carré']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','losange']],
            [['t','losange']],
            [['t','carré']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','vrai']],
            [['t','faux']],
            [['t','vrai']],
            [['t','faux']],
            [['t','losange']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','quadrilatère']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','carré']],
            [['t','parallélogramme']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','parallélogramme']],
            [['t','carré']],
            [['t','losange']],
            [['t','losange']],
            [['t','losange']]
          ],
          correction:[
            [['t','Une figure plane ayant 4 côtés est un quadrilatère']],
            [['t','Une figure plane ayant 2 diagonales est un quadrilatère']],
            [['t','Un quadrilatère ayant 3 côtés de même longueur est un losange']],
            [['t','Un quadrilatère ayant 3 angles droit est un rectangle']],
            [['t','Un quadrilatère ayant 2 côtés opposés parallèle et de même longueur est un parallélogramme']],
            [['t','Un quadrilatère ayant ses côtés opposés de même longueur 2 à 2 est un parallélogramme']],
            [['t','Un quadrilatère ayant ses angles opposés de même mesure 2 à 2 est un parallélogramme']],
            [['t','Un quadrilatère ayant ses diagonales qui se coupent en leur milieu est un parallélogramme']],
            [['t','Un parallélogramme ayant 2 côtés consécutif perpendiculaire est un rectangle']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur est un rectangle']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur est un losange']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire est un losange']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur et perpendiculaire est un losange : faux']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs perpendiculaire et de même longueur est un  carré : vrai']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur et perpendiculaire est un rectangle : faux']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire et de même longueur est un carré : vrai']],
            [['t','Un rectangle ayant ses diagonales perpendiculaire est un carré.']],
            [['t','Un rectangle ayant 2 côtés consécutifs de même longueur est un carré.']],
            [['t','Un losange ayant ses diagonales de même longueur est un carré.']],
            [['t','Un losange ayant 2 côtés consécutifs perpendiculaire est un carré.']],
            [['t','La figure est un losange'],['im','stage3niveau1-01.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-02.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-03.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-04.png']],
            [['t','La figure est un losange'],['im','stage3niveau1-05.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-06.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-07.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-08.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-09.png']],
            [['t','La figure est un losange'],['im','stage3niveau1-10.png']],
            [['t','La figure est un losange'],['im','stage3niveau1-11.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-12.png']],
            [['t','La figure est un quadrilatère'],['im','stage3niveau1-13.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-14.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-15.png']],
            [['t','La figure est un quadrilatère'],['im','stage3niveau1-16.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-17.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-18.png']],
            [['t','La figure est un quadrilatère'],['im','stage3niveau1-19.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-20.png']]
          ]
        },
        {
          stage: 'stage8',
          id: 'stage8niveau1',
          orientation: 'h',
          type: 'Quadrilatères #2',
          questions:[
            [['t','Une figure plane ayant 4 côtés est un :']],
            [['t','Une figure plane ayant 2 diagonales est un :']],
            [['t','Un quadrilatère ayant 3 côtés de même longueur est un :']],
            [['t','Un quadrilatère ayant 3 angles droit est un :']],
            [['t','Un quadrilatère ayant 2 côtés opposés parallèle et de même longueur est un :']],
            [['t','Un quadrilatère ayant ses côtés opposés de même longueur 2 à 2 est un :']],
            [['t','Un quadrilatère ayant ses angles opposés de même mesure 2 à 2 est un :']],
            [['t','Un quadrilatère ayant ses diagonales qui se coupent en leur milieu est un :']],
            [['t','Un parallélogramme ayant 2 côtés consécutif perpendiculaire est un :']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur est un :']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur est un :']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire est un :']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur et perpendiculaire est un  losange :']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs perpendiculaire et de même longueur est un  carré :']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur et perpendiculaire est un rectangle :']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire et de même longueur est un carré :']],
            [['t','Un [...] ayant ses diagonales perpendiculaire est un carré.']],
            [['t','Un [...] ayant 2 côtés consécutifs de même longueur est un carré.']],
            [['t','Un [...] ayant ses diagonales de même longueur est un carré.']],
            [['t','Un [...] ayant 2 côtés consécutifs perpendiculaire est un carré.']],
            [['im','stage3niveau1-01.png']],
            [['im','stage3niveau1-02.png']],
            [['im','stage3niveau1-03.png']],
            [['im','stage3niveau1-04.png']],
            [['im','stage3niveau1-05.png']],
            [['im','stage3niveau1-06.png']],
            [['im','stage3niveau1-07.png']],
            [['im','stage3niveau1-08.png']],
            [['im','stage3niveau1-09.png']],
            [['im','stage3niveau1-10.png']],
            [['im','stage3niveau1-11.png']],
            [['im','stage3niveau1-12.png']],
            [['im','stage3niveau1-13.png']],
            [['im','stage3niveau1-14.png']],
            [['im','stage3niveau1-15.png']],
            [['im','stage3niveau1-16.png']],
            [['im','stage3niveau1-17.png']],
            [['im','stage3niveau1-18.png']],
            [['im','stage3niveau1-19.png']],
            [['im','stage3niveau1-20.png']]
          ],
          vrai:[
            [['t','quadrilatère']],
            [['t','quadrilatère']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','losange']],
            [['t','faux']],
            [['t','vrai']],
            [['t','faux']],
            [['t','vrai']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','losange']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','parallélogramme']],
            [['t','losange']],
            [['t','parallélogramme']],
            [['t','rectangle']],
            [['t','parallélogramme']],
            [['t','parallélogramme']],
            [['t','losange']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','quadrilatère']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','quadrilatère']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','quadrilatère']],
            [['t','carré']]
          ],
          faux:[
            [['t','carré']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','losange']],
            [['t','losange']],
            [['t','carré']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','vrai']],
            [['t','faux']],
            [['t','vrai']],
            [['t','faux']],
            [['t','losange']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','losange']],
            [['t','carré']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','quadrilatère']],
            [['t','losange']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','carré']],
            [['t','parallélogramme']],
            [['t','rectangle']],
            [['t','carré']],
            [['t','parallélogramme']],
            [['t','carré']],
            [['t','losange']],
            [['t','losange']],
            [['t','losange']]
          ],
          correction:[
            [['t','Une figure plane ayant 4 côtés est un quadrilatère']],
            [['t','Une figure plane ayant 2 diagonales est un quadrilatère']],
            [['t','Un quadrilatère ayant 3 côtés de même longueur est un losange']],
            [['t','Un quadrilatère ayant 3 angles droit est un rectangle']],
            [['t','Un quadrilatère ayant 2 côtés opposés parallèle et de même longueur est un parallélogramme']],
            [['t','Un quadrilatère ayant ses côtés opposés de même longueur 2 à 2 est un parallélogramme']],
            [['t','Un quadrilatère ayant ses angles opposés de même mesure 2 à 2 est un parallélogramme']],
            [['t','Un quadrilatère ayant ses diagonales qui se coupent en leur milieu est un parallélogramme']],
            [['t','Un parallélogramme ayant 2 côtés consécutif perpendiculaire est un rectangle']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur est un rectangle']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur est un losange']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire est un losange']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs de même longueur et perpendiculaire est un losange : faux']],
            [['t','Un parallélogramme ayant 2 côtés consécutifs perpendiculaire et de même longueur est un  carré : vrai']],
            [['t','Un parallélogramme ayant ses diagonales de même longueur et perpendiculaire est un rectangle : faux']],
            [['t','Un parallélogramme ayant ses diagonales perpendiculaire et de même longueur est un carré : vrai']],
            [['t','Un rectangle ayant ses diagonales perpendiculaire est un carré.']],
            [['t','Un rectangle ayant 2 côtés consécutifs de même longueur est un carré.']],
            [['t','Un losange ayant ses diagonales de même longueur est un carré.']],
            [['t','Un losange ayant 2 côtés consécutifs perpendiculaire est un carré.']],
            [['t','La figure est un losange'],['im','stage3niveau1-01.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-02.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-03.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-04.png']],
            [['t','La figure est un losange'],['im','stage3niveau1-05.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-06.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-07.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-08.png']],
            [['t','La figure est un parallélogramme'],['im','stage3niveau1-09.png']],
            [['t','La figure est un losange'],['im','stage3niveau1-10.png']],
            [['t','La figure est un losange'],['im','stage3niveau1-11.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-12.png']],
            [['t','La figure est un quadrilatère'],['im','stage3niveau1-13.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-14.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-15.png']],
            [['t','La figure est un quadrilatère'],['im','stage3niveau1-16.png']],
            [['t','La figure est un rectangle'],['im','stage3niveau1-17.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-18.png']],
            [['t','La figure est un quadrilatère'],['im','stage3niveau1-19.png']],
            [['t','La figure est un carré'],['im','stage3niveau1-20.png']],
          ]
        }
      ]
    }
  },
  actions: {
    
  },
  getters: {
    
  }
})